// Browser integration tests with the real mp-data.js and Supabase SDK.
// Supabase HTTP responses are intercepted; no emails or production data writes.
const {chromium}=require(process.env.MP_PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..');
const catalog=require('./fixtures/backend-catalog.json');
const user={id:'00000000-0000-4000-8000-000000000001',aud:'authenticated',role:'authenticated',email:'cliente@example.test',app_metadata:{provider:'email'},user_metadata:{}};
const now=Math.floor(Date.now()/1000);
const token=[Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),Buffer.from(JSON.stringify({sub:user.id,role:'authenticated',aud:'authenticated',iat:now,exp:now+3600})).toString('base64url'),'synthetic-signature'].join('.');
const session={access_token:token,refresh_token:'synthetic-refresh',expires_at:now+3600,expires_in:3600,token_type:'bearer',user};
const profile={people:'4 pessoas',budget:'Até R$ 250',goal:'Praticidade',equipment:['Air Fryer','Fogão'],avoid:['Peixe']};
const server=http.createServer((req,res)=>{
 const url=new URL(req.url,'http://localhost');
 if(url.pathname==='/favicon.ico'){res.writeHead(204);res.end();return}
 const file=path.resolve(root,'.'+url.pathname.slice('/app-preview'.length)+(url.pathname.endsWith('/')?'index.html':''));
 if(!url.pathname.startsWith('/app-preview/')||!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return}
 const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
 res.writeHead(200,{'content-type':types[path.extname(file)]||'text/plain'});fs.createReadStream(file).pipe(res);
});
let browser,base;const passed=[];
async function test(name,fn){await fn();passed.push(name);console.log('PASS '+name)}
async function setup(options={}){
 const ctx=await browser.newContext({viewport:{width:options.width||390,height:900},serviceWorkers:options.pwa?'allow':'block'});
 await ctx.addInitScript(({saved,profile,empty,timeout})=>{if(!empty)localStorage.setItem('mp-preview-profile-v1',JSON.stringify(profile));sessionStorage.setItem('mp-ios-guide-seen','1');if(saved)localStorage.setItem('sb-uajdfknjuqhntopkbral-auth-token',JSON.stringify(saved));if(timeout){const original=window.setTimeout;window.setTimeout=(fn,ms,...args)=>original(fn,ms===20000?200:ms,...args)}},{saved:options.real?session:null,profile:options.profile||profile,empty:options.empty,timeout:options.timeout});
 const p=await ctx.newPage();const calls=[];const errors=[];const consoleErrors=[];const checked=new Map();const state={access:true};
 p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});
 await ctx.route('https://uajdfknjuqhntopkbral.supabase.co/**',async route=>{
  const req=route.request();const url=new URL(req.url());const body=req.postDataJSON();calls.push({path:url.pathname,method:req.method(),body,query:url.search});
  if(options.handle&&await options.handle(route,req,url,calls))return;
  const respond=async value=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(value)});
  if(url.pathname==='/auth/v1/user')return respond(user);
  if(url.pathname.endsWith('/rpc/mp_has_active_access'))return respond(state.access&&options.access!==false);
  if(url.pathname==='/rest/v1/mp_recipes')return respond(catalog);
  if(url.pathname.endsWith('/rpc/mp_generate_week_plan')){
   const equipment=body.p_equipment.map(v=>({'Air Fryer':'air_fryer','Fogão':'fogao','Forno':'forno'}[v]));
   const eligible=catalog.filter(r=>(!body.p_avoid_items.includes('Peixe')||!r.tags.includes('peixe'))&&(!equipment.length||r.equipment.some(e=>equipment.includes(e))));
   const meals=Array.from({length:7},(_,i)=>{const r=eligible[i%eligible.length];const date=new Date(body.p_start_date+'T12:00:00');date.setDate(date.getDate()+i);return{...r,recipe_id:r.id,meal_date:[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-'),total_minutes:r.prep_minutes+r.cook_minutes}});
   const shopping_items=[{id:'item-a',item_name:'Batata',category:'hortifruti',quantity:2.5,unit:'kg',is_checked:checked.get('item-a')||false},{id:'item-b',item_name:'Queijo muçarela',category:'laticinios',quantity:400,unit:'g',is_checked:false},{id:'item-c',item_name:'Frango',category:'proteinas',quantity:1.2,unit:'kg',is_checked:false}];
   return respond({meal_plan_id:'plan-id',shopping_list_id:'list-id',household_size:body.p_household_size,start_date:body.p_start_date,end_date:meals[6].meal_date,budget_cents:body.p_budget_cents,estimated_cost_cents:28000,within_budget:body.p_budget_cents==null?null:body.p_budget_cents>=28000,meals,shopping_items});
  }
  if(url.pathname.endsWith('/rpc/mp_find_recipes_by_ingredients'))return respond([{...catalog[4],recipe_id:catalog[4].id,matched_ingredients:2,total_required_ingredients:5},{...catalog[1],recipe_id:catalog[1].id,matched_ingredients:1,total_required_ingredients:4}]);
  if(url.pathname==='/rest/v1/mp_shopping_list_items'){
   if(req.method()==='PATCH'){const id=url.searchParams.get('id').replace('eq.','');checked.set(id,body.is_checked);return respond({id,is_checked:body.is_checked})}
   return respond([{id:'item-a',item_name:'Batata',quantity:2.5,unit:'kg',is_checked:checked.get('item-a')||false,mp_ingredients:{category:'hortifruti'}}]);
  }
  errors.push('Unexpected API request '+url.pathname);return respond(null);
 });
 if(options.pwa){const old=execFileSync('git',['show','06eb8f7:app-preview/sw.js'],{cwd:root,encoding:'utf8'});await ctx.route('**/app-preview/sw.js',r=>r.fulfill({contentType:'text/javascript',body:old}))}
 await p.goto(base);await p.waitForFunction(()=>document.body.dataset.dataMode);
 return{ctx,p,calls,errors,consoleErrors,checked,state};
}
async function nav(t,target){await t.p.locator(`[data-nav="${target}"]`).filter({visible:true}).first().click()}
async function generate(t){await nav(t,'planejar');await t.p.locator('#plannerForm button[type="submit"]').click();await t.p.locator('.day-plan').first().waitFor()}
async function screenshot(t,name){if(process.env.MP_BACKEND_ARTIFACT_DIR){await t.p.screenshot({path:path.join(process.env.MP_BACKEND_ARTIFACT_DIR,name+'.png'),fullPage:true})}}
async function noOverflow(t){assert(await t.p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))}
async function close(t,expectedErrors=false){assert.deepEqual(t.errors,[]);if(!expectedErrors)assert.deepEqual(t.consoleErrors,[]);await t.ctx.close()}
async function fail(route,status=400){await route.fulfill({status,contentType:'application/json',body:JSON.stringify({code:'synthetic_error',message:'TECHNICAL DETAILS MUST STAY IN CONSOLE'})});return true}
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${server.address().port}/app-preview/index.html`;
 browser=await chromium.launch({channel:process.env.MP_BROWSER_CHANNEL||'msedge',headless:true});
 try{
  for(const width of [320,390,1024,1440]){
   await test(`public demo and legacy budget at ${width}px`,async()=>{const t=await setup({width});assert.equal(await t.p.locator('#mpDataMode').textContent(),'Modo demonstração');await generate(t);assert.equal(await t.p.locator('.day-plan').count(),7);assert.equal(await t.p.locator('#budget').inputValue(),'250');assert.equal(JSON.parse(await t.p.evaluate(()=>localStorage.getItem('mp-preview-profile-v1'))).budget,250);await nav(t,'receitas');assert.equal(await t.p.locator('.recipe-card img').count(),3);await noOverflow(t);assert.equal(t.calls.length,0);await close(t)});
   await test(`real SDK catalog, plan, budget, restrictions, shopping, search and modal at ${width}px`,async()=>{
    const t=await setup({width,real:true});await t.p.waitForFunction(()=>document.querySelectorAll('.recipe-card').length===10);assert.equal(await t.p.locator('#mpDataMode').textContent(),'Dados salvos na sua conta');await generate(t);
    const call=t.calls.find(c=>c.path.endsWith('/rpc/mp_generate_week_plan'));assert.equal(call.body.p_budget_cents,25000);assert.equal(call.body.p_household_size,4);assert.equal(call.body.p_goal,'praticidade');assert.deepEqual(call.body.p_avoid_items,['Peixe']);assert.deepEqual(call.body.p_equipment,['Air Fryer','Fogão']);const local=await t.p.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`});assert.equal(call.body.p_start_date,local);
    assert.equal(await t.p.locator('.day-plan').count(),7);assert(!(await t.p.locator('.day-plan').allTextContents()).some(s=>s.includes('Tilápia')));assert((await t.p.locator('.plan-result__header').textContent()).includes('Este cardápio ficou acima do orçamento.'));await noOverflow(t);if(width===320||width===1440)await screenshot(t,`backend-${width}-plan`);
    for(const img of await t.p.locator('.day-plan img').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(i=>i.decode())}
    await nav(t,'compras');assert.equal(await t.p.locator('.list-group').count(),3);assert.equal(await t.p.locator('#shoppingList input').count(),3);const item=t.p.locator('[data-item-id="item-a"]');await item.check();await t.p.waitForFunction(()=>!document.querySelector('[data-item-id="item-a"]').disabled);assert.equal(t.checked.get('item-a'),true);assert.equal(await t.p.locator('#progressText').textContent(),'33%');await noOverflow(t);if(width===320||width===1440)await screenshot(t,`backend-${width}-shopping`);
    await nav(t,'receitas');await t.p.locator('#ingredientInput').fill('frango, batata, queijo');await t.p.locator('#ingredientForm button').click();await t.p.waitForFunction(()=>document.querySelectorAll('.recipe-card').length===2);assert.deepEqual(t.calls.find(c=>c.path.endsWith('/rpc/mp_find_recipes_by_ingredients')).body.p_ingredients,['frango','batata','queijo']);assert.equal(await t.p.locator('.recipe-card h3').first().textContent(),catalog[4].title);assert.match(await t.p.locator('.mp-recipe-match').first().textContent(),/2 de 5/);
    await t.p.locator('.recipe-card button').first().click();assert.equal(await t.p.locator('#recipeModal h2').textContent(),catalog[4].title);assert.match(await t.p.locator('#recipeModal .eyebrow').textContent(),/4 porções/);assert.equal(await t.p.locator('.modal-columns ul li').count(),catalog[4].mp_recipe_ingredients.length);assert.equal(await t.p.locator('.modal-columns ol li').first().textContent(),catalog[4].instructions[0]);await t.p.locator('.modal-visual img').evaluate(i=>i.decode());if(width===320||width===1440)await screenshot(t,`backend-${width}-modal`);await t.p.locator('[data-recipe-action="shopping"]').click();await t.p.waitForFunction(()=>document.querySelectorAll('#shoppingList input').length===1);assert.equal(await item.isChecked(),true);assert(t.calls.some(c=>c.method==='GET'&&c.query.includes('shopping_list_id=eq.list-id')));await close(t);
   });
  }
  await test('free decimal budget, zero/no limit, goal and equipment forwarding',async()=>{const t=await setup({real:true});await generate(t);await t.p.locator('#budget').fill('123.45');await t.p.locator('label[for="g3"]').click();await t.p.locator('label[for="e1"]').click();await t.p.locator('label[for="e2"]').click();await t.p.locator('label[for="e3"]').click();await t.p.locator('#plannerForm button[type="submit"]').click();await t.p.waitForFunction(()=>!document.querySelector('#plannerForm button[type="submit"]').disabled);let call=t.calls.filter(c=>c.path.endsWith('/rpc/mp_generate_week_plan')).at(-1);assert.equal(call.body.p_budget_cents,12345);assert.equal(call.body.p_goal,'variedade');assert.deepEqual(call.body.p_equipment,['Forno']);for(const value of ['0','']){await t.p.locator('#budget').fill(value);await t.p.locator('#plannerForm button[type="submit"]').click();await t.p.waitForFunction(()=>!document.querySelector('#plannerForm button[type="submit"]').disabled);call=t.calls.filter(c=>c.path.endsWith('/rpc/mp_generate_week_plan')).at(-1);assert.equal(call.body.p_budget_cents,value===''?null:0)}await close(t)});
  await test('numeric onboarding and invalid budget validation',async()=>{const t=await setup({empty:true});await t.p.locator('.mp-next').click();await t.p.locator('#obBudget').fill('-1');await t.p.locator('.mp-next').click();assert(await t.p.locator('[data-step="1"]').evaluate(e=>e.classList.contains('is-active')));await t.p.locator('#obBudget').fill('287.50');await t.p.locator('.mp-next').click();await t.p.locator('.mp-next').click();await t.p.locator('.mp-next').click();await t.p.locator('.mp-onboarding').waitFor({state:'detached'});assert.equal(JSON.parse(await t.p.evaluate(()=>localStorage.getItem('mp-preview-profile-v1'))).budget,287.5);await close(t)});
  await test('no entitlement uses demo without catalog or plan RPC',async()=>{const t=await setup({real:true,access:false});await generate(t);assert.equal(await t.p.locator('#mpDataMode').textContent(),'Modo demonstração');assert(!t.calls.some(c=>c.path.endsWith('/mp_recipes')||c.path.endsWith('/rpc/mp_generate_week_plan')));await close(t)});
  await test('session/access expiry returns to demo without generating in the account',async()=>{const t=await setup({real:true});await t.p.waitForFunction(()=>document.querySelectorAll('.recipe-card').length===10);t.state.access=false;await nav(t,'planejar');await t.p.locator('#plannerForm button[type="submit"]').click();await t.p.waitForFunction(()=>document.body.dataset.dataMode==='demo');assert(!t.calls.some(c=>c.path.endsWith('/rpc/mp_generate_week_plan')));assert.equal(await t.p.locator('#plannerForm button[type="submit"]').isDisabled(),false);await nav(t,'receitas');assert.equal(await t.p.locator('.recipe-card').count(),3);await close(t,true)});
  await test('catalog failure has retry and keeps real mode',async()=>{let reject=true;const t=await setup({real:true,handle:async(r,q,u)=>u.pathname.endsWith('/mp_recipes')&&reject?fail(r):false});await nav(t,'receitas');await t.p.getByText('Tentar carregar receitas novamente').waitFor();reject=false;await t.p.getByText('Tentar carregar receitas novamente').click();await t.p.waitForFunction(()=>document.querySelectorAll('.recipe-card').length===10);assert.equal(await t.p.locator('body').getAttribute('data-data-mode'),'real');await close(t,true)});
  await test('plan, search and checkbox failures restore controls and keep technical details out of UI',async()=>{let target='';const t=await setup({real:true,handle:async(r,q,u)=>u.pathname.endsWith(target)&&target?fail(r):false});await generate(t);target='/rpc/mp_generate_week_plan';await t.p.locator('#plannerForm button[type="submit"]').click();await t.p.waitForFunction(()=>!document.querySelector('#plannerForm button[type="submit"]').disabled);assert.equal(await t.p.locator('.day-plan').count(),7);target='/rpc/mp_find_recipes_by_ingredients';await nav(t,'receitas');await t.p.locator('#ingredientInput').fill('frango');await t.p.locator('#ingredientForm button').click();await t.p.waitForFunction(()=>!document.querySelector('#ingredientForm button').disabled);target='/mp_shopping_list_items';await nav(t,'compras');const item=t.p.locator('[data-item-id="item-a"]');await item.check();await t.p.waitForFunction(()=>!document.querySelector('[data-item-id="item-a"]').disabled);assert.equal(await item.isChecked(),false);assert(!(await t.p.locator('body').textContent()).includes('TECHNICAL DETAILS'));await close(t,true)});
  await test('shopping reload failure can be retried',async()=>{let reject=false;const t=await setup({real:true,handle:async(r,q,u)=>u.pathname.endsWith('/mp_shopping_list_items')&&q.method()==='GET'&&reject?fail(r):false});await generate(t);await nav(t,'compras');reject=true;await t.p.locator('#mpRefreshShopping').click();await t.p.waitForFunction(()=>!document.querySelector('#mpRefreshShopping').disabled);assert.equal(await t.p.locator('#shoppingList input').count(),3);reject=false;await t.p.locator('#mpRefreshShopping').click();await t.p.waitForFunction(()=>document.querySelectorAll('#shoppingList input').length===1);await close(t,true)});
  await test('expired server session uses demo',async()=>{const t=await setup({real:true,handle:async(r,q,u)=>u.pathname==='/auth/v1/user'?fail(r,401):false});assert.equal(await t.p.locator('body').getAttribute('data-data-mode'),'demo');await generate(t);assert(!t.calls.some(c=>c.path.endsWith('/rpc/mp_generate_week_plan')));await close(t,true)});
  await test('plan timeout always restores button',async()=>{const t=await setup({real:true,timeout:true,handle:async(r,q,u)=>{if(u.pathname.endsWith('/rpc/mp_generate_week_plan')){await new Promise(resolve=>setTimeout(resolve,500));await fail(r);return true}return false}});await nav(t,'planejar');await t.p.locator('#plannerForm button[type="submit"]').click();await t.p.waitForFunction(()=>!document.querySelector('#plannerForm button[type="submit"]').disabled);await close(t,true)});
  await test('PWA v8 to v9 migration, module precache, auth rules and offline demo',async()=>{
   const old=execFileSync('git',['show','06eb8f7:app-preview/sw.js'],{cwd:root,encoding:'utf8'});
   const t=await setup({pwa:true});await t.p.waitForFunction(()=>navigator.serviceWorker.controller?.state==='activated');await t.p.waitForFunction(async()=>navigator.serviceWorker.controller?.state==='activated'&&(await caches.keys()).includes('mundo-pratico-preview-v8'));await t.p.waitForLoadState('networkidle');await t.p.evaluate(()=>caches.open('unrelated-keep'));await t.ctx.unroute('**/app-preview/sw.js');await t.p.evaluate(async()=>{const r=await navigator.serviceWorker.ready;const done=new Promise((resolve,reject)=>{setTimeout(()=>reject(new Error('Service worker upgrade timed out')),30000);r.addEventListener('updatefound',()=>{const w=r.installing;w.addEventListener('statechange',()=>{if(w.state==='activated')resolve()})},{once:true})});await r.update();await done});const keys=await t.p.evaluate(()=>caches.keys());assert(keys.includes('mundo-pratico-preview-v9'));assert(!keys.includes('mundo-pratico-preview-v8'));assert(keys.includes('unrelated-keep'));const assets=await t.p.evaluate(async()=>{const c=await caches.open('mundo-pratico-preview-v9');return(await c.keys()).map(r=>new URL(r.url).pathname)});assert(assets.some(p=>p.endsWith('/mp-data.js')));assert(!assets.some(p=>/\/(acesso\.(html|js|css)|supabase-config\.js)$/.test(p)));await t.ctx.setOffline(true);await t.p.reload();await t.p.waitForFunction(()=>document.body.dataset.dataMode==='demo');await generate(t);assert.equal(await t.p.locator('.day-plan').count(),7);await close(t);
  });
  console.log(JSON.stringify({passed:passed.length,api:'real module and SDK with intercepted HTTP',productionWrites:false}));
 }finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
