"""Curated recipe catalogs for the Mundo Prático Air Fryer collection."""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha1
import re


@dataclass(frozen=True)
class Recipe:
    title: str
    category: str
    description: str
    yield_text: str
    minutes: int
    temperature: int
    ingredients: tuple[str, ...]
    steps: tuple[str, ...]
    tip: str


def _pick(title: str, options: list[str]) -> str:
    return options[int(sha1(title.encode("utf-8")).hexdigest(), 16) % len(options)]


def _description(title: str, subject: str, highlight: str, family: str) -> str:
    templates = {
        "roast": [
            "{Subject} ganha sabor com {highlight} e fica dourado sem complicação.",
            "Uma combinação prática de {subject} com {highlight}, feita em poucos passos.",
            "{Subject} bem temperado com {highlight}, ideal para uma refeição descomplicada.",
        ],
        "breaded": [
            "Casquinha firme, interior macio e o sabor marcante de {highlight}.",
            "Um empanado sequinho de {subject}, valorizado por {highlight}.",
            "{Subject} crocante por fora e suculento por dentro, com {highlight}.",
        ],
        "stuffed": [
            "Recheio de {highlight} em uma porção prática, dourada e cheia de textura.",
            "{Subject} recebe um recheio de {highlight} e vai direto para a Air Fryer.",
            "Uma receita caprichada de {subject}, com {highlight} no centro.",
        ],
        "bake": [
            "Massa macia com {highlight}, assada em porções fáceis de servir.",
            "Uma fornada pequena e aromática, preparada com {highlight}.",
            "Textura delicada e sabor de {highlight} em uma receita prática.",
        ],
        "gratin": [
            "Camadas cremosas de {subject}, finalizadas com {highlight}.",
            "{Subject} bem quente, com cobertura dourada de {highlight}.",
            "Uma porção reconfortante de {subject}, gratinada com {highlight}.",
        ],
        "egg": [
            "Ovos macios com {highlight}, preparados em porções individuais.",
            "Uma refeição rápida de ovos com {highlight} e bordas levemente douradas.",
            "Ovos e {highlight} formam uma combinação simples para qualquer hora.",
        ],
        "vegetable": [
            "{Subject} dourado com {highlight}, preservando boa textura.",
            "Um acompanhamento colorido de {subject}, realçado por {highlight}.",
            "{Subject} ganha bordas tostadas e o aroma de {highlight}.",
        ],
        "pastry": [
            "Massa dourada e recheio de {highlight} em uma porção fácil de compartilhar.",
            "Uma opção assada com recheio bem temperado de {highlight}.",
            "Casquinha assada e centro saboroso de {highlight}.",
        ],
        "sweet": [
            "Uma sobremesa de {subject} com {highlight}, feita em pequena porção.",
            "{Subject} ganha aroma e doçura com {highlight}.",
            "Textura macia e sabor de {highlight} para finalizar a refeição.",
        ],
    }
    clean_subject = re.sub(r"^(?:os|as|o|a)\s+", "", subject, flags=re.IGNORECASE)
    return _pick(title, templates[family]).format(
        subject=clean_subject,
        Subject=clean_subject[0].upper() + clean_subject[1:],
        highlight=highlight,
    )


def R(
    title: str,
    category: str,
    family: str,
    subject: str,
    highlight: str,
    yield_text: str,
    minutes: int,
    temperature: int,
    main: str,
    extras: list[str],
    tip: str,
) -> Recipe:
    ingredients = tuple([main, *extras])
    cook = max(6, minutes - (8 if family in {"breaded", "stuffed", "pastry"} else 5))
    if family == "roast":
        steps = (
            f"Preaqueça a Air Fryer a {temperature} °C por 3 minutos.",
            f"Coloque {subject} em uma tigela e envolva com os demais ingredientes até temperar por igual.",
            "Distribua na cesta sem sobrepor as peças e reserve o tempero que restar na tigela.",
            f"Asse por {cook} minutos, virando ou mexendo na metade do tempo.",
            "Confira o ponto, deixe descansar por 2 minutos e sirva com o tempero da cesta.",
        )
    elif family == "breaded":
        steps = (
            f"Preaqueça a Air Fryer a {temperature} °C por 3 minutos.",
            f"Tempere {subject} e organize os ingredientes do empanado em recipientes separados.",
            "Passe cada porção na camada úmida e depois na cobertura seca, pressionando levemente.",
            "Acomode na cesta em uma só camada e borrife ou pincele uma fina camada de azeite.",
            f"Asse por {cook} minutos, vire na metade e retire quando a crosta estiver dourada.",
        )
    elif family == "stuffed":
        steps = (
            f"Preaqueça a Air Fryer a {temperature} °C por 3 minutos.",
            f"Prepare {subject} para receber o recheio, retirando excesso de umidade quando necessário.",
            "Misture os ingredientes do recheio até obter uma textura uniforme e prove o tempero.",
            "Recheie as porções sem apertar demais e acomode-as em recipiente que caiba na cesta.",
            f"Asse por {cook} minutos, até o centro estar quente e a superfície dourada.",
        )
    elif family == "bake":
        steps = (
            f"Preaqueça a Air Fryer a {temperature} °C por 3 minutos.",
            "Misture primeiro os ingredientes úmidos e incorpore os secos sem bater em excesso.",
            "Divida a massa em forminhas untadas, preenchendo no máximo três quartos da capacidade.",
            f"Asse por {cook} minutos e faça o teste do palito no centro.",
            "Espere 5 minutos antes de desenformar para a massa firmar.",
        )
    elif family == "gratin":
        steps = (
            f"Preaqueça a Air Fryer a {temperature} °C por 3 minutos.",
            f"Prepare {subject} e misture com os ingredientes cremosos e os temperos.",
            "Transfira para um refratário baixo que caiba na cesta e nivele a superfície.",
            "Espalhe os ingredientes da cobertura por cima, sem pressionar.",
            f"Asse por {cook} minutos, até borbulhar nas bordas e dourar no centro.",
        )
    elif family == "egg":
        steps = (
            f"Preaqueça a Air Fryer a {temperature} °C por 3 minutos.",
            "Bata os ovos apenas até misturar claras e gemas; junte os temperos e os complementos.",
            "Unte ramequins ou forminhas de silicone e distribua a mistura sem encher até a borda.",
            f"Asse por {cook} minutos, verificando o centro nos minutos finais.",
            "Retire quando os ovos estiverem firmes, mas ainda úmidos, e sirva imediatamente.",
        )
    elif family == "vegetable":
        steps = (
            f"Preaqueça a Air Fryer a {temperature} °C por 3 minutos.",
            f"Seque bem {subject} e corte em tamanhos semelhantes para cozinhar por igual.",
            "Misture com o azeite e os temperos, cobrindo todos os lados.",
            f"Asse por {cook} minutos em uma só camada, mexendo na metade do tempo.",
            "Ajuste o sal e finalize com os ingredientes reservados para servir.",
        )
    elif family == "pastry":
        steps = (
            f"Preaqueça a Air Fryer a {temperature} °C por 3 minutos.",
            "Prepare o recheio, misturando os ingredientes até ficar úmido, mas sem líquido solto.",
            f"Modele {subject}, distribua o recheio e feche bem as bordas.",
            "Pincele a superfície, acomode na cesta com espaço entre as unidades e asse em levas.",
            f"Asse por {cook} minutos, virando se necessário, até dourar por igual.",
        )
    else:  # sweet
        steps = (
            f"Preaqueça a Air Fryer a {temperature} °C por 3 minutos.",
            f"Prepare {subject} e misture delicadamente com os ingredientes aromáticos.",
            "Distribua em forma ou ramequins untados que caibam na cesta.",
            f"Asse por {cook} minutos, observando a textura nos minutos finais.",
            "Deixe amornar antes de servir para que os sabores e a estrutura se assentem.",
        )
    return Recipe(
        title=title,
        category=category,
        description=_description(title, subject, highlight, family),
        yield_text=yield_text,
        minutes=minutes,
        temperature=temperature,
        ingredients=ingredients,
        steps=steps,
        tip=tip,
    )


FIT_CATEGORIES = [
    "Frangos e Carnes",
    "Legumes e Acompanhamentos",
    "Lanches Low Carb",
    "Café da Manhã e Refeições Rápidas",
    "Doces e Sobremesas Fit",
]


FIT_RECIPES = [
    # Frangos e Carnes
    R("Cubos de frango ao limão-siciliano e sálvia", FIT_CATEGORIES[0], "roast", "os cubos de frango", "limão-siciliano e sálvia", "3 porções", 24, 190, "500 g de peito de frango em cubos", ["1 colher (sopa) de azeite", "raspas e suco de 1/2 limão-siciliano", "1 colher (chá) de sálvia seca", "1 dente de alho amassado", "sal e pimenta-do-reino a gosto"], "Corte os cubos no mesmo tamanho para que terminem de assar juntos."),
    R("Sobrecoxa desossada com iogurte e cúrcuma", FIT_CATEGORIES[0], "roast", "as sobrecoxas", "iogurte, cúrcuma e limão", "4 porções", 32, 190, "600 g de sobrecoxas de frango desossadas", ["3 colheres (sopa) de iogurte natural", "1 colher (chá) de cúrcuma", "1/2 colher (chá) de cominho", "1 colher (sopa) de suco de limão", "sal a gosto"], "Retire o excesso de marinada antes de levar à cesta para dourar melhor."),
    R("Almôndegas de frango, abobrinha e hortelã", FIT_CATEGORIES[0], "roast", "as almôndegas", "abobrinha e hortelã", "14 unidades", 25, 190, "500 g de frango moído", ["1/2 abobrinha ralada e espremida", "2 colheres (sopa) de farelo de aveia", "1 colher (sopa) de hortelã picada", "1 ovo", "1/2 colher (chá) de páprica", "sal a gosto"], "Esprema muito bem a abobrinha para as almôndegas manterem o formato."),
    R("Filé suíno com crosta de mostarda e linhaça", FIT_CATEGORIES[0], "roast", "os filés suínos", "mostarda, linhaça e alecrim", "3 porções", 26, 190, "500 g de filé-mignon suíno em medalhões", ["1 colher (sopa) de mostarda", "2 colheres (sopa) de linhaça dourada moída", "1 colher (chá) de alecrim", "1 colher (sopa) de azeite", "sal e pimenta-do-reino a gosto"], "Pressione a linhaça sobre a carne para formar uma crosta uniforme."),
    R("Kafta de patinho com tahine e cheiro-verde", FIT_CATEGORIES[0], "roast", "as kaftas", "tahine, cominho e cheiro-verde", "8 unidades", 23, 200, "500 g de patinho moído", ["1 colher (sopa) de tahine", "2 colheres (sopa) de cheiro-verde picado", "1/2 cebola pequena ralada", "1/2 colher (chá) de cominho", "sal e pimenta-síria a gosto"], "Modele porções finas para que cozinhem por dentro sem ressecar."),
    R("Iscas de carne com pimentão e chimichurri", FIT_CATEGORIES[0], "roast", "as iscas de carne", "pimentões e chimichurri", "3 porções", 20, 200, "450 g de coxão mole em tiras", ["1/2 pimentão vermelho em tiras", "1/2 pimentão amarelo em tiras", "1 colher (sopa) de azeite", "1 colher (chá) de chimichurri", "sal a gosto"], "Se a cesta for pequena, faça duas levas para a carne selar em vez de cozinhar no vapor."),
    R("Rolinhos de frango com ricota e espinafre", FIT_CATEGORIES[0], "stuffed", "os filés de frango", "ricota, espinafre e noz-moscada", "4 unidades", 31, 190, "4 filés finos de peito de frango", ["120 g de ricota amassada", "1/2 xícara (chá) de espinafre picado", "1 colher (chá) de azeite", "1 pitada de noz-moscada", "sal e pimenta-do-reino a gosto"], "Prenda cada rolinho com palitos e lembre-se de removê-los antes de servir."),
    R("Hambúrguer de peru com aveia e páprica", FIT_CATEGORIES[0], "roast", "os hambúrgueres", "aveia, páprica e cebola", "4 unidades", 22, 190, "500 g de peito de peru moído", ["3 colheres (sopa) de aveia em flocos finos", "2 colheres (sopa) de cebola ralada", "1 colher (chá) de páprica doce", "1 colher (chá) de azeite", "sal a gosto"], "Faça uma pequena depressão no centro para o hambúrguer não estufar."),
    R("Asinhas com curry suave e leite de coco", FIT_CATEGORIES[0], "roast", "as asinhas", "curry, leite de coco e gengibre", "4 porções", 35, 200, "700 g de meio da asa de frango", ["3 colheres (sopa) de leite de coco", "1 colher (chá) de curry suave", "1/2 colher (chá) de gengibre ralado", "1 colher (chá) de azeite", "sal a gosto"], "Seque as asinhas antes de temperar; a pele ficará mais dourada."),
    R("Mini rocambole de carne com cenoura e ervas", FIT_CATEGORIES[0], "stuffed", "a massa de carne", "cenoura, salsinha e queijo minas", "4 porções", 34, 190, "500 g de carne moída magra", ["1 cenoura pequena ralada", "80 g de queijo minas padrão em tiras", "2 colheres (sopa) de salsinha picada", "2 colheres (sopa) de farelo de aveia", "1 ovo", "sal e pimenta a gosto"], "Modele sobre papel-manteiga perfurado e retire o papel nos minutos finais."),

    # Legumes e Acompanhamentos
    R("Chuchu gratinado com ricota e castanha", FIT_CATEGORIES[1], "gratin", "o chuchu cozido", "ricota, castanha e noz-moscada", "4 porções", 23, 180, "2 chuchus cozidos al dente em cubos", ["150 g de ricota amassada", "3 colheres (sopa) de castanha-do-pará picada", "30 g de parmesão ralado", "1 pitada de noz-moscada", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Escorra e seque o chuchu para o gratinado não acumular água."),
    R("Berinjela assada com tahine e romã", FIT_CATEGORIES[1], "vegetable", "as rodelas de berinjela", "tahine, limão e sementes de romã", "3 porções", 22, 190, "1 berinjela grande em rodelas de 1 cm", ["1 colher (sopa) de azeite", "1 colher (sopa) de tahine", "1 colher (sopa) de suco de limão", "2 colheres (sopa) de sementes de romã", "sal e cominho a gosto"], "Sirva o tahine e a romã apenas depois de assar para preservar o contraste de texturas."),
    R("Couve-flor dourada com cúrcuma e gergelim", FIT_CATEGORIES[1], "vegetable", "os floretes de couve-flor", "cúrcuma, gergelim e limão", "4 porções", 20, 200, "500 g de couve-flor em floretes", ["1 colher (sopa) de azeite", "1 colher (chá) de cúrcuma", "1 colher (sopa) de gergelim", "1 colher (sopa) de suco de limão", "sal e pimenta a gosto"], "Mantenha os floretes de tamanho parecido e deixe espaço para o ar circular."),
    R("Brócolis gratinado com creme de ricota", FIT_CATEGORIES[1], "gratin", "os floretes de brócolis", "creme de ricota e parmesão", "3 porções", 20, 180, "350 g de brócolis levemente cozido", ["120 g de creme de ricota", "30 g de parmesão ralado", "1 dente de alho ralado", "1 pitada de noz-moscada", "sal e pimenta a gosto"], "Use brócolis ainda firme, pois ele continuará cozinhando durante o gratinado."),
    R("Quiabo crocante com páprica defumada", FIT_CATEGORIES[1], "vegetable", "os quiabos", "páprica defumada e limão", "3 porções", 18, 200, "350 g de quiabos inteiros e secos", ["1 colher (sopa) de azeite", "1 colher (chá) de páprica defumada", "1 colher (sopa) de suco de limão", "1/2 colher (chá) de alho em pó", "sal a gosto"], "Lave com antecedência e seque completamente para reduzir a umidade."),
    R("Cabotiá em gomos com canela e tomilho", FIT_CATEGORIES[1], "vegetable", "os gomos de abóbora", "canela, tomilho e pimenta", "4 porções", 26, 190, "600 g de abóbora cabotiá em gomos finos", ["1 colher (sopa) de azeite", "1/2 colher (chá) de canela", "1 colher (chá) de tomilho", "1 pitada de pimenta calabresa", "sal a gosto"], "A casca pode permanecer: ela amacia e ajuda os gomos a manterem o formato."),
    R("Cogumelos recheados com espinafre e cottage", FIT_CATEGORIES[1], "stuffed", "os cogumelos", "espinafre, cottage e alho", "10 unidades", 18, 180, "10 cogumelos paris grandes sem os talos", ["100 g de queijo cottage", "1/2 xícara (chá) de espinafre picado", "1 dente de alho ralado", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Não lave os cogumelos em água corrente; limpe com pano úmido para não encharcar."),
    R("Cebola-roxa recheada com lentilha e queijo minas", FIT_CATEGORIES[1], "stuffed", "as cebolas", "lentilha, queijo minas e tomilho", "4 unidades", 28, 180, "4 cebolas-roxas médias pré-cozidas por 6 minutos", ["1 xícara (chá) de lentilha cozida e escorrida", "100 g de queijo minas em cubos", "1 colher (chá) de tomilho", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Deixe duas camadas externas inteiras para a cebola sustentar o recheio."),
    R("Vagem tostada com parmesão e limão", FIT_CATEGORIES[1], "vegetable", "as vagens", "parmesão, limão e alho", "3 porções", 17, 190, "350 g de vagem com as pontas retiradas", ["1 colher (sopa) de azeite", "30 g de parmesão ralado fino", "raspas de 1/2 limão", "1/2 colher (chá) de alho em pó", "sal a gosto"], "Acrescente o parmesão nos 4 minutos finais para evitar que escureça demais."),
    R("Repolho em gomos com mostarda e ervas", FIT_CATEGORIES[1], "vegetable", "os gomos de repolho", "mostarda, tomilho e vinagre", "4 porções", 24, 190, "1/2 repolho pequeno cortado em 4 gomos", ["1 colher (sopa) de azeite", "1 colher (sopa) de mostarda", "1 colher (chá) de tomilho", "1 colher (chá) de vinagre de maçã", "sal e pimenta a gosto"], "Mantenha parte do talo em cada gomo para que as folhas não se soltem."),

    # Lanches Low Carb
    R("Nuvem salgada de cream cheese e orégano", FIT_CATEGORIES[2], "bake", "a massa aerada", "cream cheese, orégano e claras em neve", "6 unidades", 22, 160, "3 ovos, com claras e gemas separadas", ["3 colheres (sopa) de cream cheese", "30 g de parmesão ralado", "1/2 colher (chá) de fermento químico", "1/2 colher (chá) de orégano", "1 pitada de sal"], "Incorpore as claras com movimentos suaves para preservar o volume."),
    R("Empadinha de frango com massa de amêndoas", FIT_CATEGORIES[2], "pastry", "as empadinhas", "frango, farinha de amêndoas e requeijão", "6 unidades", 27, 170, "1 xícara (chá) de farinha de amêndoas", ["1 ovo", "2 colheres (sopa) de azeite", "1 xícara (chá) de frango cozido e desfiado", "2 colheres (sopa) de requeijão", "2 colheres (sopa) de tomate picado", "sal e páprica a gosto"], "Use forminhas de silicone para desenformar a massa delicada com facilidade."),
    R("Mini pizza de abobrinha com pesto", FIT_CATEGORIES[2], "gratin", "as rodelas de abobrinha", "pesto, muçarela e tomate-cereja", "10 unidades", 17, 190, "1 abobrinha grande em rodelas grossas", ["2 colheres (sopa) de molho pesto", "100 g de muçarela ralada", "5 tomates-cereja em metades", "1 colher (chá) de azeite", "sal a gosto"], "Asse a abobrinha por 4 minutos antes de cobrir para evitar excesso de água."),
    R("Bolinho de atum, abobrinha e limão", FIT_CATEGORIES[2], "roast", "os bolinhos", "atum, abobrinha e raspas de limão", "8 unidades", 22, 190, "1 lata de atum em água bem escorrido", ["1/2 abobrinha ralada e espremida", "1 ovo", "3 colheres (sopa) de farinha de amêndoas", "raspas de 1/2 limão", "1 colher (sopa) de salsinha", "sal e pimenta a gosto"], "Resfrie a massa por 10 minutos se estiver macia demais para modelar."),
    R("Cestinha de peito de peru com ovo e alho-poró", FIT_CATEGORIES[2], "egg", "as cestinhas", "alho-poró, queijo minas e pimenta", "6 unidades", 18, 170, "6 fatias de peito de peru", ["3 ovos", "1/3 de xícara (chá) de alho-poró fatiado", "60 g de queijo minas em cubos", "1 colher (sopa) de cheiro-verde", "pimenta-do-reino a gosto"], "Forre bem o fundo da forma com o peito de peru para o ovo não escapar."),
    R("Nuggets de couve-flor com queijo curado", FIT_CATEGORIES[2], "breaded", "os nuggets de couve-flor", "queijo curado, páprica e cebolinha", "12 unidades", 25, 190, "2 xícaras (chá) de couve-flor cozida e picada", ["1 ovo", "70 g de queijo curado ralado", "3 colheres (sopa) de farinha de amêndoas", "1 colher (sopa) de cebolinha", "1/2 colher (chá) de páprica", "azeite para pincelar", "sal a gosto"], "Amasse apenas parte da couve-flor para manter pequenos pedaços e dar textura."),
    R("Quiche sem massa de alho-poró e ricota", FIT_CATEGORIES[2], "egg", "a mistura de ovos", "alho-poró, ricota e noz-moscada", "4 porções", 25, 170, "4 ovos", ["150 g de ricota amassada", "1/2 xícara (chá) de alho-poró fatiado", "3 colheres (sopa) de leite", "1 pitada de noz-moscada", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Use um refratário baixo para o centro cozinhar antes de as bordas ressecarem."),
    R("Muffin salgado de queijo, chia e tomate", FIT_CATEGORIES[2], "bake", "a massa de muffin", "queijo, chia e tomate", "6 unidades", 24, 170, "3 ovos", ["1/2 xícara (chá) de farinha de amêndoas", "80 g de muçarela ralada", "1 tomate pequeno sem sementes em cubos", "1 colher (sopa) de chia", "1/2 colher (chá) de fermento químico", "sal e orégano a gosto"], "Se o topo dourar cedo, cubra as forminhas sem encostar na massa."),
    R("Rolinho de abobrinha com presunto e provolone", FIT_CATEGORIES[2], "stuffed", "as lâminas de abobrinha", "presunto, provolone e manjericão", "8 unidades", 20, 190, "1 abobrinha grande em lâminas finas", ["8 fatias finas de presunto", "80 g de provolone em tiras", "8 folhas de manjericão", "1 colher (chá) de azeite", "pimenta-do-reino a gosto"], "Sele as lâminas por 3 minutos antes de enrolar para ficarem flexíveis."),
    R("Tortinha de carne com crosta de queijo", FIT_CATEGORIES[2], "gratin", "a carne temperada", "tomate, queijo e páprica", "4 unidades", 28, 180, "350 g de carne moída", ["1/2 xícara (chá) de tomate picado", "100 g de muçarela ralada", "2 colheres (sopa) de cebola picada", "1 ovo", "1/2 colher (chá) de páprica", "sal e pimenta a gosto"], "Faça porções baixas para a carne cozinhar antes de o queijo dourar demais."),

    # Café da Manhã e Refeições Rápidas
    R("Ovos assados com tomate-cereja e espinafre", FIT_CATEGORIES[3], "egg", "os ovos", "tomate-cereja, espinafre e queijo", "2 porções", 16, 170, "4 ovos", ["8 tomates-cereja em metades", "1/2 xícara (chá) de espinafre picado", "40 g de queijo minas ralado", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Para gema mais cremosa, comece a verificar 2 minutos antes do tempo indicado."),
    R("Muffin de ovos com brócolis e cebola-roxa", FIT_CATEGORIES[3], "egg", "a mistura de ovos", "brócolis, cebola-roxa e cúrcuma", "6 unidades", 20, 170, "4 ovos", ["1/2 xícara (chá) de brócolis picado", "2 colheres (sopa) de cebola-roxa picada", "40 g de parmesão ralado", "1 pitada de cúrcuma", "sal e pimenta a gosto"], "Pique o brócolis pequeno para ele cozinhar no mesmo tempo dos ovos."),
    R("Granola de castanhas, coco e sementes", FIT_CATEGORIES[3], "sweet", "a mistura de castanhas", "coco, canela e sementes", "8 porções", 18, 150, "1 xícara (chá) de castanhas variadas picadas", ["1/2 xícara (chá) de coco em lascas", "2 colheres (sopa) de sementes de abóbora", "2 colheres (sopa) de sementes de girassol", "1 colher (sopa) de óleo de coco", "1 colher (chá) de canela", "1 colher (sopa) de adoçante culinário"], "Mexa a cada 4 minutos: castanhas passam do dourado ao queimado rapidamente."),
    R("Abacate assado com ovo e pimenta rosa", FIT_CATEGORIES[3], "egg", "as metades de abacate", "ovo, limão e pimenta rosa", "2 porções", 17, 170, "1 abacate pequeno firme cortado ao meio", ["2 ovos pequenos", "1 colher (chá) de suco de limão", "1 colher (chá) de azeite", "1 colher (chá) de cebolinha", "sal e pimenta rosa a gosto"], "Retire um pouco da polpa para acomodar o ovo sem transbordar."),
    R("Panquequinha assada de coco e canela", FIT_CATEGORIES[3], "bake", "a massa de panqueca", "coco, canela e baunilha", "4 unidades", 18, 160, "2 ovos", ["3 colheres (sopa) de farinha de coco", "1/3 de xícara (chá) de leite", "1 colher (chá) de adoçante culinário", "1/2 colher (chá) de canela", "1/2 colher (chá) de fermento químico", "1/2 colher (chá) de essência de baunilha"], "A farinha de coco absorve líquido; espere 2 minutos antes de avaliar a consistência."),
    R("Frittata de cogumelos, rúcula e parmesão", FIT_CATEGORIES[3], "egg", "a mistura de ovos", "cogumelos, rúcula e parmesão", "3 porções", 23, 170, "5 ovos", ["1 xícara (chá) de cogumelos fatiados", "1/2 xícara (chá) de rúcula picada", "40 g de parmesão ralado", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Salteie os cogumelos por 4 minutos na Air Fryer antes de juntar aos ovos."),
    R("Bolinho de ricota, ervas e linhaça", FIT_CATEGORIES[3], "roast", "os bolinhos de ricota", "ervas, linhaça e limão", "10 unidades", 20, 180, "250 g de ricota amassada", ["1 ovo", "3 colheres (sopa) de linhaça dourada moída", "2 colheres (sopa) de cheiro-verde", "raspas de 1/2 limão", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Umedeça as mãos com água para modelar sem acrescentar mais farinha."),
    R("Tofu dourado com tomate e gergelim", FIT_CATEGORIES[3], "roast", "os cubos de tofu", "tomate, gergelim e shoyu", "2 porções", 22, 190, "300 g de tofu firme em cubos", ["1 tomate sem sementes em cubos", "1 colher (sopa) de shoyu com teor reduzido de sódio", "1 colher (chá) de óleo de gergelim", "1 colher (sopa) de gergelim", "1 colher (chá) de amido de milho", "cebolinha a gosto"], "Pressione o tofu entre papéis-toalha por 15 minutos para melhorar o dourado."),
    R("Tomate grande com ovo, cottage e cebolinha", FIT_CATEGORIES[3], "stuffed", "os tomates", "ovo, cottage e cebolinha", "2 porções", 20, 170, "2 tomates grandes e firmes sem a polpa", ["2 ovos pequenos", "4 colheres (sopa) de queijo cottage", "1 colher (sopa) de cebolinha", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Coloque os tomates em ramequins para mantê-los estáveis dentro da cesta."),
    R("Pãozinho de linhaça com queijo e ervas", FIT_CATEGORIES[3], "bake", "a massa do pãozinho", "linhaça, queijo e alecrim", "4 unidades", 22, 170, "1/2 xícara (chá) de linhaça dourada moída", ["2 ovos", "80 g de queijo minas ralado", "2 colheres (sopa) de iogurte natural", "1/2 colher (chá) de fermento químico", "1/2 colher (chá) de alecrim", "1 pitada de sal"], "Espere a massa descansar por 3 minutos para a linhaça hidratar."),

    # Doces e Sobremesas Fit
    R("Flan assado de coco e baunilha", FIT_CATEGORIES[4], "bake", "o creme de coco", "coco, baunilha e limão", "4 unidades", 27, 150, "3 ovos", ["1 xícara (chá) de leite de coco", "3 colheres (sopa) de coco ralado sem açúcar", "2 colheres (sopa) de adoçante culinário", "1/2 colher (chá) de baunilha", "raspas de 1/2 limão"], "Asse em ramequins cobertos e gele por 2 horas antes de servir."),
    R("Pera assada com cacau e creme de iogurte", FIT_CATEGORIES[4], "sweet", "as peras", "cacau, canela e iogurte", "4 porções", 20, 170, "2 peras firmes cortadas ao meio", ["1 colher (sopa) de cacau em pó", "1/2 colher (chá) de canela", "1 colher (chá) de adoçante culinário", "1 colher (chá) de óleo de coco", "1/2 xícara (chá) de iogurte natural"], "Sirva o iogurte frio sobre a pera morna para criar contraste."),
    R("Muffin de beterraba, cacau e aveia", FIT_CATEGORIES[4], "bake", "a massa de muffin", "beterraba, cacau e laranja", "6 unidades", 26, 160, "1/2 xícara (chá) de beterraba cozida e amassada", ["1 ovo", "1/2 xícara (chá) de aveia em flocos finos", "2 colheres (sopa) de cacau em pó", "2 colheres (sopa) de adoçante culinário", "raspas de 1/2 laranja", "1 colher (chá) de fermento químico"], "Processe a beterraba até obter um purê liso para a massa ficar uniforme."),
    R("Brownie de cacau e feijão-preto", FIT_CATEGORIES[4], "bake", "a massa de brownie", "cacau, feijão-preto e baunilha", "6 pedaços", 25, 160, "1 xícara (chá) de feijão-preto cozido e escorrido", ["1 ovo", "3 colheres (sopa) de cacau em pó", "3 colheres (sopa) de adoçante culinário", "2 colheres (sopa) de óleo de coco", "1/2 colher (chá) de baunilha", "1/2 colher (chá) de fermento químico"], "Bata o feijão até ficar completamente liso antes de misturar os demais ingredientes."),
    R("Cocadinha macia de coco e limão", FIT_CATEGORIES[4], "sweet", "a massa de coco", "coco, limão e leite de coco", "10 unidades", 19, 160, "1 xícara (chá) de coco seco sem açúcar", ["1 ovo", "3 colheres (sopa) de leite de coco", "2 colheres (sopa) de adoçante culinário", "raspas de 1 limão", "1/2 colher (chá) de essência de baunilha"], "Modele porções compactas para que as bordas dourem sem a cocada se desfazer."),
    R("Cheesecake individual de iogurte e frutas vermelhas", FIT_CATEGORIES[4], "bake", "o creme de cheesecake", "iogurte, baunilha e frutas vermelhas", "4 unidades", 25, 150, "200 g de cream cheese", ["1/2 xícara (chá) de iogurte natural", "1 ovo", "2 colheres (sopa) de adoçante culinário", "1/2 colher (chá) de baunilha", "1/2 xícara (chá) de frutas vermelhas"], "Leve à geladeira por pelo menos 2 horas para o centro adquirir textura cremosa."),
    R("Bolinho de cenoura com amêndoas e laranja", FIT_CATEGORIES[4], "bake", "a massa de cenoura", "amêndoas, laranja e canela", "6 unidades", 26, 160, "1 cenoura pequena ralada fino", ["2 ovos", "3/4 de xícara (chá) de farinha de amêndoas", "3 colheres (sopa) de adoçante culinário", "raspas de 1/2 laranja", "1/2 colher (chá) de canela", "1 colher (chá) de fermento químico"], "Rale a cenoura bem fina para ela cozinhar no curto tempo da Air Fryer."),
    R("Trufa assada de ricota, cacau e castanhas", FIT_CATEGORIES[4], "bake", "a massa de ricota", "cacau, castanhas e laranja", "10 unidades", 20, 160, "200 g de ricota bem amassada", ["3 colheres (sopa) de cacau em pó", "3 colheres (sopa) de castanhas moídas", "2 colheres (sopa) de adoçante culinário", "1 ovo", "raspas de 1/2 laranja", "1 pitada de sal"], "Resfrie a massa por 15 minutos para modelar porções regulares."),
    R("Biscoito macio de amendoim e banana", FIT_CATEGORIES[4], "bake", "a massa de biscoito", "amendoim, banana e canela", "12 unidades", 18, 160, "1 banana madura amassada", ["1/2 xícara (chá) de pasta de amendoim sem açúcar", "1/2 xícara (chá) de farinha de amendoim", "1/2 colher (chá) de canela", "1 colher (sopa) de cacau em nibs", "1 pitada de sal"], "Achate os biscoitos antes de assar, pois a massa quase não se espalha."),
    R("Quadradinho de coco, limão e chia", FIT_CATEGORIES[4], "bake", "a massa de coco", "limão, chia e baunilha", "8 pedaços", 23, 160, "1 xícara (chá) de coco ralado sem açúcar", ["2 ovos", "1/3 de xícara (chá) de leite de coco", "2 colheres (sopa) de chia", "2 colheres (sopa) de adoçante culinário", "raspas de 1 limão", "1/2 colher (chá) de baunilha"], "Espere esfriar por completo antes de cortar para obter quadrados firmes."),
]


SPECIAL_CATEGORIES = [
    "Lanches e Salgados",
    "Carnes e Frangos",
    "Refeições Rápidas",
    "Doces e Sobremesas",
]


SPECIAL_RECIPES = [
    # Lanches e Salgados
    R("Cestinha crocante de brie e damasco", SPECIAL_CATEGORIES[0], "pastry", "as cestinhas", "brie, damasco e castanhas", "10 unidades", 22, 180, "10 quadrados de massa filo ou massa para pastel", ["150 g de queijo brie em cubos", "8 damascos secos picados", "3 colheres (sopa) de castanhas picadas", "1 colher (sopa) de manteiga derretida", "1 colher (chá) de tomilho"], "Acomode a massa em forminhas para segurar o queijo durante o derretimento."),
    R("Croquete de frango com milho e queijo", SPECIAL_CATEGORIES[0], "breaded", "os croquetes", "milho, muçarela e páprica", "14 unidades", 30, 190, "2 xícaras (chá) de frango cozido e desfiado", ["1/2 xícara (chá) de milho", "100 g de muçarela em cubos", "3 colheres (sopa) de requeijão", "1 ovo batido", "1 xícara (chá) de farinha panko", "1/2 colher (chá) de páprica", "azeite para pincelar e sal a gosto"], "Feche bem a massa ao redor do queijo para o recheio não escapar."),
    R("Cestinha de parmesão com caponata", SPECIAL_CATEGORIES[0], "stuffed", "as cestinhas de parmesão", "berinjela, pimentão e azeitona", "10 unidades", 24, 180, "200 g de parmesão ralado", ["1 berinjela pequena em cubos", "1/2 pimentão vermelho em cubos", "3 colheres (sopa) de azeitona picada", "1 colher (sopa) de azeite", "1 colher (chá) de vinagre", "sal e orégano a gosto"], "Modele o parmesão ainda morno sobre forminhas invertidas e recheie depois de frio."),
    R("Mini quiche de cebola caramelizada e bacon", SPECIAL_CATEGORIES[0], "bake", "a massa das quiches", "cebola, bacon e queijo", "6 unidades", 30, 170, "6 discos pequenos de massa para pastel", ["3 ovos", "1/2 xícara (chá) de creme de leite", "1 cebola pequena fatiada e dourada", "80 g de bacon já frito", "60 g de queijo meia-cura ralado", "sal e pimenta a gosto"], "Use bacon e cebola já frios para não amolecer a massa antes de assar."),
    R("Samosa assada de frango e ervilha", SPECIAL_CATEGORIES[0], "pastry", "as samosas", "frango, ervilha e curry", "10 unidades", 27, 190, "10 tiras largas de massa para pastel", ["250 g de frango desfiado", "1/2 xícara (chá) de ervilha", "1/2 colher (chá) de curry", "2 colheres (sopa) de iogurte natural", "1 gema para pincelar", "sal e coentro a gosto"], "Dobre a massa em triângulos e mantenha o recheio seco para as pontas colarem."),
    R("Cigarrete de presunto, queijo e mostarda", SPECIAL_CATEGORIES[0], "pastry", "os cigarretes", "presunto, muçarela e mostarda", "8 unidades", 22, 190, "8 retângulos de massa para pastel", ["8 fatias de presunto", "8 palitos de muçarela", "2 colheres (sopa) de mostarda", "1 gema para pincelar", "1 colher (chá) de orégano"], "Dobre as laterais antes de enrolar para segurar o queijo derretido."),
    R("Croquete de peixe com batata-doce e dill", SPECIAL_CATEGORIES[0], "breaded", "os croquetes de peixe", "batata-doce, dill e limão", "14 unidades", 30, 190, "300 g de peixe branco cozido e desfiado", ["250 g de batata-doce cozida e amassada", "1 ovo batido", "1 xícara (chá) de farinha panko", "1 colher (sopa) de dill ou salsinha", "raspas de 1 limão", "azeite para borrifar, sal e pimenta a gosto"], "Resfrie a mistura antes de modelar para o croquete manter o formato."),
    R("Coxinha cremosa de frango e páprica", SPECIAL_CATEGORIES[0], "breaded", "as coxinhas", "frango, requeijão e páprica", "12 unidades", 34, 190, "2 xícaras (chá) de massa cozida para coxinha", ["1 e 1/2 xícara (chá) de frango desfiado", "3 colheres (sopa) de requeijão", "1/2 colher (chá) de páprica", "1 ovo batido", "1 xícara (chá) de farinha panko", "azeite para borrifar"], "Congele por 15 minutos depois de empanar para firmar a coxinha."),
    R("Mini strudel salgado de linguiça e maçã", SPECIAL_CATEGORIES[0], "pastry", "os mini strudels", "linguiça, maçã e mostarda", "8 unidades", 28, 180, "8 retângulos de massa folhada gelada", ["250 g de linguiça sem pele já dourada", "1 maçã pequena em cubos", "1 colher (sopa) de mostarda", "1 colher (chá) de tomilho", "1 gema para pincelar", "pimenta-do-reino a gosto"], "Deixe o recheio esfriar completamente antes de fechar a massa folhada."),
    R("Trouxinha árabe de carne e coalhada", SPECIAL_CATEGORIES[0], "pastry", "as trouxinhas", "carne, coalhada e zaatar", "8 unidades", 30, 190, "8 discos pequenos de massa para pastel", ["300 g de carne moída refogada", "4 colheres (sopa) de coalhada seca", "1/2 cebola pequena picada", "1 colher (chá) de zaatar", "1 gema para pincelar", "sal e salsinha a gosto"], "Feche três pontas no centro e deixe o recheio frio para a massa permanecer firme."),
    R("Roseta de massa com calabresa e provolone", SPECIAL_CATEGORIES[0], "pastry", "as rosetas", "calabresa, provolone e cebola-roxa", "8 unidades", 28, 190, "8 tiras largas de massa fresca para pizza", ["150 g de calabresa ralada", "1/2 cebola-roxa fatiada fino", "120 g de provolone ralado", "3 colheres (sopa) de molho de tomate", "1 gema para pincelar", "orégano a gosto"], "Enrole cada tira como uma rosa e asse apoiada em forminha de muffin."),
    R("Nó de massa com pesto e muçarela", SPECIAL_CATEGORIES[0], "pastry", "os nós de massa", "pesto, muçarela e parmesão", "10 unidades", 23, 180, "400 g de massa fresca para pizza em tiras", ["3 colheres (sopa) de molho pesto", "120 g de muçarela ralada", "30 g de parmesão ralado", "1 gema para pincelar", "1 colher (chá) de orégano"], "Faça nós frouxos para a massa crescer e o recheio permanecer entre as voltas."),
    R("Cebola recheada com carne e provolone", SPECIAL_CATEGORIES[0], "stuffed", "as cebolas", "carne, provolone e tomilho", "4 unidades", 35, 180, "4 cebolas médias pré-cozidas por 8 minutos", ["250 g de carne moída refogada", "100 g de provolone em cubos", "1 colher (chá) de tomilho", "2 colheres (sopa) de farinha de rosca", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Retire o miolo com cuidado e deixe duas camadas externas para a cebola não romper."),
    R("Canapé de polenta com queijo e tomate assado", SPECIAL_CATEGORIES[0], "gratin", "os discos de polenta", "queijo, tomate e manjericão", "12 unidades", 25, 190, "12 discos de polenta firme e fria", ["120 g de queijo meia-cura em cubos", "6 tomates-cereja em metades", "1 colher (sopa) de azeite", "12 folhas de manjericão", "sal e pimenta a gosto"], "Doure os discos por 8 minutos antes de acrescentar a cobertura."),
    R("Camarão empanado com tapioca e limão", SPECIAL_CATEGORIES[0], "breaded", "os camarões", "tapioca granulada, limão e páprica", "4 porções", 20, 190, "400 g de camarões médios limpos", ["1 ovo batido", "1/2 xícara (chá) de tapioca granulada", "1/2 xícara (chá) de farinha panko", "raspas de 1 limão", "1/2 colher (chá) de páprica", "azeite para borrifar e sal a gosto"], "Pressione a tapioca sobre o camarão e retire assim que a crosta dourar."),
    R("Queijo coalho crocante com melaço picante", SPECIAL_CATEGORIES[0], "breaded", "os cubos de queijo", "gergelim, melaço e pimenta", "4 porções", 16, 190, "300 g de queijo coalho em cubos grandes", ["1 ovo batido", "1/2 xícara (chá) de farinha panko", "2 colheres (sopa) de gergelim", "2 colheres (sopa) de melaço de cana", "1 pitada de pimenta calabresa", "azeite para borrifar"], "Congele o queijo por 20 minutos para ele dourar antes de derreter demais."),
    R("Bruschetta de cogumelos e parmesão", SPECIAL_CATEGORIES[0], "gratin", "as fatias de pão", "cogumelos, parmesão e tomilho", "8 unidades", 18, 190, "8 fatias de pão italiano", ["200 g de cogumelos fatiados", "50 g de parmesão ralado", "1 dente de alho", "1 colher (sopa) de azeite", "1 colher (chá) de tomilho", "sal e pimenta a gosto"], "Doure primeiro o pão por 3 minutos e só depois acrescente a cobertura."),
    R("Nachos de pão sírio com creme de feijão", SPECIAL_CATEGORIES[0], "roast", "os triângulos de pão sírio", "páprica, feijão e limão", "5 porções", 18, 190, "3 pães sírios cortados em triângulos", ["1 colher (sopa) de azeite", "1/2 colher (chá) de páprica", "1 xícara (chá) de feijão cozido e escorrido", "1 colher (sopa) de suco de limão", "1 dente de alho", "sal e cominho a gosto"], "Processe o creme separadamente e sirva frio com os nachos ainda mornos."),
    R("Bolinho de mandioca com carne-seca e coentro", SPECIAL_CATEGORIES[0], "breaded", "os bolinhos de mandioca", "carne-seca, coentro e queijo", "12 unidades", 32, 190, "2 xícaras (chá) de mandioca cozida e amassada", ["1 xícara (chá) de carne-seca dessalgada e desfiada", "80 g de queijo coalho em cubos", "2 colheres (sopa) de coentro picado", "1 ovo batido", "1 xícara (chá) de farinha panko", "azeite para borrifar"], "A mandioca deve estar fria e seca antes de modelar para não pedir farinha em excesso."),
    R("Empanada de frango, requeijão e azeitona", SPECIAL_CATEGORIES[0], "pastry", "as empanadas", "frango, requeijão e azeitona", "8 unidades", 30, 190, "8 discos de massa para empanada", ["250 g de frango desfiado", "3 colheres (sopa) de requeijão", "3 colheres (sopa) de azeitona picada", "2 colheres (sopa) de tomate picado", "1 gema para pincelar", "sal e páprica a gosto"], "Aperte as bordas com um garfo e leve à geladeira por 10 minutos antes de assar."),
    R("Folhado de queijo, tomate seco e manjericão", SPECIAL_CATEGORIES[0], "pastry", "os folhados", "queijo, tomate seco e manjericão", "8 unidades", 24, 180, "300 g de massa folhada gelada em quadrados", ["150 g de muçarela em cubos", "80 g de tomate seco picado", "8 folhas de manjericão", "1 gema para pincelar", "1 colher (chá) de gergelim"], "Mantenha a massa fria até o momento de assar para formar camadas leves."),
    R("Tirinhas de peixe com crosta de limão e ervas", SPECIAL_CATEGORIES[0], "breaded", "as tiras de peixe", "limão, ervas e panko", "4 porções", 22, 190, "500 g de filé de peixe firme em tiras", ["1 ovo batido", "1 xícara (chá) de farinha panko", "raspas de 1 limão", "2 colheres (sopa) de salsinha picada", "1/2 colher (chá) de alho em pó", "azeite para borrifar, sal e pimenta a gosto"], "Seque o peixe antes de empanar para a crosta aderir melhor."),
    R("Mini hambúrguer recheado com cheddar", SPECIAL_CATEGORIES[0], "stuffed", "os mini hambúrgueres", "cheddar, cebola e molho inglês", "8 unidades", 25, 190, "600 g de carne moída", ["120 g de cheddar em cubos", "2 colheres (sopa) de cebola ralada", "1 colher (sopa) de molho inglês", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Use dois discos finos de carne e sele bem a emenda ao redor do queijo."),
    R("Pimentão recheado com linguiça e queijo", SPECIAL_CATEGORIES[0], "stuffed", "as metades de pimentão", "linguiça, muçarela e tomate", "6 metades", 31, 180, "3 pimentões pequenos cortados ao meio", ["300 g de linguiça sem a pele", "120 g de muçarela ralada", "1 tomate sem sementes em cubos", "2 colheres (sopa) de cebola picada", "1 colher (chá) de orégano"], "Escolha pimentões de base estável ou apoie-os em um refratário baixo."),
    R("Ovo escocês de codorna com crosta de ervas", SPECIAL_CATEGORIES[0], "breaded", "os ovos envolvidos em carne", "linguiça, ervas e panko", "12 unidades", 28, 190, "12 ovos de codorna cozidos e descascados", ["400 g de linguiça sem a pele", "1 ovo batido", "1 xícara (chá) de farinha panko", "2 colheres (sopa) de salsinha picada", "1/2 colher (chá) de mostarda", "azeite para borrifar"], "Faça uma camada fina e uniforme de carne ao redor de cada ovo."),

    # Carnes e Frangos
    R("Frango hasselback caprese", SPECIAL_CATEGORIES[1], "stuffed", "os filés de frango", "muçarela, tomate e manjericão", "4 porções", 34, 190, "4 filés altos de peito de frango", ["120 g de muçarela em fatias", "2 tomates pequenos em meias-luas", "12 folhas de manjericão", "1 colher (sopa) de azeite", "1 colher (chá) de orégano", "sal e pimenta a gosto"], "Faça cortes profundos sem atravessar completamente o filé e encaixe o recheio."),
    R("Sobrecoxa recheada com farofa de ervas", SPECIAL_CATEGORIES[1], "stuffed", "as sobrecoxas", "farofa, bacon e ervas", "4 porções", 42, 190, "4 sobrecoxas grandes desossadas", ["1/2 xícara (chá) de farinha de mandioca", "60 g de bacon já dourado", "2 colheres (sopa) de cebola picada", "2 colheres (sopa) de salsinha", "1 colher (sopa) de azeite", "sal e pimenta a gosto"], "Amarre com barbante culinário para o recheio permanecer no centro."),
    R("Lombo suíno com barbecue de goiabada", SPECIAL_CATEGORIES[1], "roast", "as fatias de lombo", "goiabada, tomate e páprica", "5 porções", 36, 190, "700 g de lombo suíno em fatias grossas", ["80 g de goiabada cremosa", "3 colheres (sopa) de molho de tomate", "1 colher (sopa) de vinagre de maçã", "1 colher (chá) de páprica defumada", "1 colher (sopa) de azeite", "sal e pimenta a gosto"], "Pincele o molho nos 8 minutos finais para não caramelizar antes da carne cozinhar."),
    R("Medalhão suíno com bacon, maçã e sálvia", SPECIAL_CATEGORIES[1], "roast", "os medalhões suínos", "bacon, maçã e sálvia", "4 porções", 32, 190, "600 g de filé-mignon suíno em medalhões", ["8 fatias finas de bacon", "1 maçã pequena em gomos", "1 colher (chá) de sálvia seca", "1 colher (sopa) de azeite", "sal e pimenta a gosto"], "Prenda o bacon com palito e remova-o antes de servir."),
    R("Bife à rolê com cenoura e provolone", SPECIAL_CATEGORIES[1], "stuffed", "os bifes", "cenoura, provolone e molho de tomate", "6 unidades", 40, 190, "6 bifes finos de coxão mole", ["1 cenoura em palitos", "120 g de provolone em palitos", "1/2 cebola em tiras", "1/2 xícara (chá) de molho de tomate", "1 colher (sopa) de azeite", "sal e pimenta a gosto"], "Escolha bifes finos e feche com dois palitos cruzados para não abrir."),
    R("Maminha com crosta de alho e parmesão", SPECIAL_CATEGORIES[1], "roast", "a peça de maminha", "alho, parmesão e tomilho", "6 porções", 45, 200, "900 g de maminha em peça que caiba na cesta", ["3 dentes de alho amassados", "50 g de parmesão ralado", "1 colher (chá) de tomilho", "1 colher (sopa) de mostarda", "1 colher (sopa) de azeite", "sal e pimenta a gosto"], "Deixe a carne descansar por 8 minutos antes de fatiar contra as fibras."),
    R("Costelinha suína com laranja e alecrim", SPECIAL_CATEGORIES[1], "roast", "as costelinhas", "laranja, alecrim e mel", "5 porções", 48, 190, "900 g de costelinha suína em ripas", ["suco e raspas de 1 laranja", "1 colher (sopa) de mel", "1 colher (chá) de alecrim", "1 dente de alho amassado", "1 colher (sopa) de azeite", "sal e pimenta a gosto"], "Cozinhe em duas levas se as ripas não couberem sem sobreposição."),
    R("Frango empanado com biscoito e parmesão", SPECIAL_CATEGORIES[1], "breaded", "os filés de frango", "biscoito salgado, parmesão e tomilho", "4 porções", 28, 190, "500 g de filés finos de peito de frango", ["1 ovo batido", "1 e 1/2 xícara (chá) de biscoito salgado triturado", "50 g de parmesão ralado", "1 colher (chá) de tomilho", "1/2 colher (chá) de alho em pó", "azeite para borrifar, sal e pimenta a gosto"], "Triture o biscoito de modo irregular para criar uma crosta com mais textura."),
    R("Peito de frango recheado com brócolis e cheddar", SPECIAL_CATEGORIES[1], "stuffed", "os peitos de frango", "brócolis, cheddar e noz-moscada", "4 porções", 36, 190, "4 filés altos de peito de frango", ["1 xícara (chá) de brócolis picado", "120 g de cheddar ralado", "2 colheres (sopa) de cream cheese", "1 pitada de noz-moscada", "1 colher (sopa) de azeite", "sal e pimenta a gosto"], "Pique o brócolis bem pequeno para o recheio aquecer por completo."),
    R("Tiras de carne acebolada com manteiga de ervas", SPECIAL_CATEGORIES[1], "roast", "as tiras de carne", "cebola, manteiga e ervas", "4 porções", 22, 200, "600 g de alcatra em tiras grossas", ["1 cebola grande em pétalas", "1 colher (sopa) de manteiga", "1 colher (chá) de ervas finas", "1 colher (chá) de molho inglês", "sal e pimenta a gosto"], "Junte a manteiga apenas nos 3 minutos finais para perfumar sem queimar."),
    R("Cupim já cozido com crosta de barbecue", SPECIAL_CATEGORIES[1], "roast", "as fatias de cupim", "barbecue, cominho e cebola", "5 porções", 25, 200, "700 g de cupim previamente cozido em fatias", ["1/2 xícara (chá) de molho barbecue", "1/2 colher (chá) de cominho", "1 cebola em pétalas", "1 colher (sopa) de azeite", "sal e pimenta a gosto"], "Esta receita parte do cupim macio e cozido; a Air Fryer serve para aquecer e criar crosta."),
    R("Linguiça toscana recheada com vinagrete e queijo", SPECIAL_CATEGORIES[1], "stuffed", "as linguiças", "vinagrete, muçarela e orégano", "6 unidades", 32, 190, "6 linguiças toscanas grossas", ["1 tomate sem sementes picado", "1/2 cebola pequena picada", "120 g de muçarela ralada", "2 colheres (sopa) de cheiro-verde", "1 colher (chá) de orégano"], "Faça um corte longitudinal sem separar a linguiça e pressione o recheio no centro."),
    R("Kafta recheada com muçarela e hortelã", SPECIAL_CATEGORIES[1], "stuffed", "as kaftas", "muçarela, hortelã e pimenta-síria", "8 unidades", 26, 200, "600 g de carne moída", ["120 g de muçarela em palitos", "2 colheres (sopa) de hortelã picada", "1/2 cebola ralada", "1/2 colher (chá) de pimenta-síria", "1 colher (sopa) de azeite", "sal a gosto"], "Feche a carne sem deixar o queijo aparente e gire os espetos na metade."),
    R("Espetinho de alcatra com pão de alho", SPECIAL_CATEGORIES[1], "roast", "os espetinhos", "alho, pão e pimentão", "6 unidades", 26, 200, "500 g de alcatra em cubos", ["2 pães franceses em cubos grandes", "1/2 pimentão vermelho em cubos", "2 colheres (sopa) de manteiga", "2 dentes de alho ralados", "2 colheres (sopa) de salsinha", "sal e pimenta a gosto"], "Coloque o pão apenas nos minutos finais ou use espetos separados para não ressecar."),
    R("Frango satay com molho de amendoim", SPECIAL_CATEGORIES[1], "roast", "os espetinhos de frango", "amendoim, gengibre e limão", "6 unidades", 26, 190, "600 g de peito de frango em tiras", ["2 colheres (sopa) de shoyu", "1 colher (chá) de gengibre ralado", "1 colher (sopa) de suco de limão", "3 colheres (sopa) de pasta de amendoim", "3 colheres (sopa) de água", "1 colher (chá) de mel"], "Use metade do molho para temperar e reserve a outra metade limpa para servir."),
    R("Picanha suína com chimichurri e limão", SPECIAL_CATEGORIES[1], "roast", "as fatias de picanha suína", "chimichurri, limão e alho", "5 porções", 34, 200, "800 g de picanha suína em fatias grossas", ["1 colher (sopa) de chimichurri", "raspas e suco de 1/2 limão", "2 dentes de alho amassados", "1 colher (sopa) de azeite", "sal e pimenta a gosto"], "Comece com a capa de gordura voltada para cima e vire na metade do tempo."),
    R("Frango cordon bleu com mostarda", SPECIAL_CATEGORIES[1], "breaded", "os filés recheados", "presunto, queijo e mostarda", "4 porções", 34, 190, "4 filés finos de peito de frango", ["4 fatias de presunto", "4 fatias de muçarela", "2 colheres (sopa) de mostarda", "1 ovo batido", "1 xícara (chá) de farinha panko", "azeite para borrifar, sal e pimenta a gosto"], "Feche as laterais com palitos e retire-os antes de servir."),
    R("Barriga suína em cubos com cinco especiarias", SPECIAL_CATEGORIES[1], "roast", "os cubos de barriga suína", "gengibre, canela e anis", "5 porções", 42, 200, "800 g de barriga suína em cubos", ["1 colher (sopa) de shoyu", "1 colher (chá) de gengibre ralado", "1/4 de colher (chá) de canela", "1 pitada de anis-estrelado moído", "1 colher (chá) de mel", "sal a gosto"], "Escorra a gordura acumulada na metade do tempo com cuidado e recoloque a cesta."),
    R("Almôndega recheada com provolone e manjericão", SPECIAL_CATEGORIES[1], "stuffed", "as almôndegas", "provolone, manjericão e tomate", "12 unidades", 30, 190, "600 g de carne moída", ["120 g de provolone em cubos", "2 colheres (sopa) de manjericão picado", "3 colheres (sopa) de farinha de rosca", "1 ovo", "1/2 xícara (chá) de molho de tomate", "sal e pimenta a gosto"], "Sirva o molho aquecido à parte para manter a superfície das almôndegas dourada."),
    R("Coxa de frango com crosta de parmesão e alho", SPECIAL_CATEGORIES[1], "breaded", "as coxas de frango", "parmesão, alho e páprica", "5 porções", 40, 190, "5 coxas de frango sem pele", ["60 g de parmesão ralado", "1 xícara (chá) de farinha panko", "1 ovo batido", "1 colher (chá) de alho em pó", "1/2 colher (chá) de páprica", "azeite para borrifar, sal e pimenta a gosto"], "Faça dois cortes rasos na parte mais grossa para o cozimento ficar uniforme."),
    R("Rosbife com mostarda em grãos e tomilho", SPECIAL_CATEGORIES[1], "roast", "a peça de carne", "mostarda em grãos, tomilho e alho", "6 porções", 38, 200, "900 g de lagarto ou filé-mignon em peça", ["2 colheres (sopa) de mostarda em grãos", "1 colher (chá) de tomilho", "2 dentes de alho amassados", "1 colher (sopa) de azeite", "sal e pimenta a gosto"], "Use termômetro culinário para escolher o ponto e deixe a carne descansar antes de fatiar."),
    R("Filé suíno com abacaxi, gengibre e gergelim", SPECIAL_CATEGORIES[1], "roast", "os cubos de filé suíno", "abacaxi, gengibre e gergelim", "4 porções", 30, 190, "600 g de filé suíno em cubos", ["1 xícara (chá) de abacaxi em cubos", "1 colher (chá) de gengibre ralado", "1 colher (sopa) de shoyu", "1 colher (sopa) de gergelim", "1 colher (chá) de mel", "1 colher (chá) de azeite"], "Acrescente o abacaxi na metade do tempo para ele dourar sem desmanchar."),
    R("Bolo de carne barbecue com centro de queijo", SPECIAL_CATEGORIES[1], "stuffed", "a massa de carne", "barbecue, muçarela e cebola", "6 porções", 42, 180, "800 g de carne moída", ["150 g de muçarela em tiras", "1/2 xícara (chá) de molho barbecue", "1/2 cebola ralada", "1 ovo", "1/2 xícara (chá) de farinha de rosca", "sal e pimenta a gosto"], "Use uma forma de bolo inglês que deixe espaço nas laterais da cesta."),
    R("Espetinho de frango com bacon e damasco", SPECIAL_CATEGORIES[1], "roast", "os espetinhos", "bacon, damasco e alecrim", "6 unidades", 28, 190, "500 g de peito de frango em cubos", ["120 g de bacon em cubos", "12 damascos secos cortados ao meio", "1 colher (chá) de alecrim", "1 colher (sopa) de azeite", "sal e pimenta a gosto"], "Alterne os ingredientes sem apertar para o ar alcançar todos os lados."),
    R("Bisteca com crosta de cebola e páprica", SPECIAL_CATEGORIES[1], "breaded", "as bistecas", "cebola, páprica e mostarda", "4 porções", 32, 190, "4 bistecas suínas", ["1 xícara (chá) de cebola crocante triturada", "2 colheres (sopa) de mostarda", "1/2 colher (chá) de páprica", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Pressione a crosta apenas de um lado e cozinhe primeiro com ela voltada para cima."),

    # Refeições Rápidas
    R("Lasanha de pão sírio com frango cremoso", SPECIAL_CATEGORIES[2], "gratin", "as camadas de pão sírio", "frango, tomate e requeijão", "4 porções", 30, 180, "2 pães sírios cortados no formato do refratário", ["2 xícaras (chá) de frango desfiado", "1 xícara (chá) de molho de tomate", "4 colheres (sopa) de requeijão", "150 g de muçarela ralada", "1 colher (chá) de orégano"], "Monte no máximo três camadas para o centro aquecer rapidamente."),
    R("Conchiglione recheado com ricota e espinafre", SPECIAL_CATEGORIES[2], "gratin", "os conchigliones cozidos", "ricota, espinafre e tomate", "4 porções", 30, 180, "16 conchigliones cozidos al dente", ["250 g de ricota amassada", "1 xícara (chá) de espinafre picado", "1 e 1/2 xícara (chá) de molho de tomate", "100 g de muçarela ralada", "1 pitada de noz-moscada", "sal e pimenta a gosto"], "Recheie a massa fria e acomode as conchas em uma única camada."),
    R("Escondidinho de mandioquinha e carne-seca", SPECIAL_CATEGORIES[2], "gratin", "o purê de mandioquinha", "carne-seca, queijo coalho e cebola", "4 porções", 32, 180, "3 xícaras (chá) de purê de mandioquinha", ["2 xícaras (chá) de carne-seca dessalgada e desfiada", "1/2 cebola fatiada e dourada", "120 g de queijo coalho ralado", "2 colheres (sopa) de creme de leite", "cheiro-verde a gosto"], "Faça camadas baixas em refratário largo para aquecer de forma uniforme."),
    R("Penne gratinado com brócolis e bacon", SPECIAL_CATEGORIES[2], "gratin", "o penne cozido", "brócolis, bacon e molho branco", "4 porções", 27, 180, "3 xícaras (chá) de penne cozido al dente", ["1 xícara (chá) de brócolis picado", "100 g de bacon já dourado", "1 xícara (chá) de molho branco", "120 g de muçarela ralada", "sal, pimenta e noz-moscada a gosto"], "Cozinhe a massa um minuto a menos que o indicado para ela terminar no molho."),
    R("Arroz de forno com frango, milho e requeijão", SPECIAL_CATEGORIES[2], "gratin", "o arroz cozido", "frango, milho e requeijão", "5 porções", 28, 180, "3 xícaras (chá) de arroz cozido", ["1 e 1/2 xícara (chá) de frango desfiado", "1/2 xícara (chá) de milho", "4 colheres (sopa) de requeijão", "120 g de muçarela ralada", "2 colheres (sopa) de cheiro-verde", "sal e pimenta a gosto"], "Solte o arroz com um garfo antes de misturar para o gratinado não ficar compacto."),
    R("Cuscuz paulista individual de sardinha", SPECIAL_CATEGORIES[2], "bake", "a massa de cuscuz", "sardinha, ervilha e tomate", "4 unidades", 28, 170, "1 e 1/2 xícara (chá) de farinha de milho flocada", ["1 lata de sardinha escorrida", "1/2 xícara (chá) de molho de tomate", "1/3 de xícara (chá) de ervilha", "1 tomate pequeno picado", "1 e 1/2 xícara (chá) de caldo quente", "sal e cheiro-verde a gosto"], "Hidrate a farinha até ficar úmida e firme; não deixe caldo acumulado nas formas."),
    R("Torta rápida de palmito e azeitona", SPECIAL_CATEGORIES[2], "bake", "a massa da torta", "palmito, azeitona e tomate", "6 porções", 34, 170, "1 xícara (chá) de leite", ["2 ovos", "1 xícara (chá) de farinha de trigo", "1 colher (sopa) de fermento químico", "1 xícara (chá) de palmito picado", "3 colheres (sopa) de azeitona", "1 tomate sem sementes picado", "sal e orégano a gosto"], "Escorra bem o palmito e o tomate para a massa assar sem ficar úmida."),
    R("Omelete de forno com linguiça e queijo", SPECIAL_CATEGORIES[2], "egg", "a mistura de ovos", "linguiça, queijo e cebola", "4 porções", 26, 170, "6 ovos", ["200 g de linguiça sem pele já dourada", "100 g de muçarela ralada", "1/2 cebola pequena picada", "2 colheres (sopa) de leite", "2 colheres (sopa) de cheiro-verde", "sal e pimenta a gosto"], "Use a linguiça já cozida e fria para não soltar gordura em excesso."),
    R("Quibe assado recheado com requeijão", SPECIAL_CATEGORIES[2], "stuffed", "a massa de quibe", "requeijão, hortelã e cebola", "6 porções", 38, 180, "2 xícaras (chá) de trigo para quibe hidratado e espremido", ["500 g de carne moída", "5 colheres (sopa) de requeijão firme", "1/2 cebola ralada", "3 colheres (sopa) de hortelã picada", "1 colher (sopa) de azeite", "sal e pimenta-síria a gosto"], "Faça duas camadas finas de quibe e mantenha o requeijão longe das bordas."),
    R("Canelone de abobrinha com carne e ricota", SPECIAL_CATEGORIES[2], "stuffed", "as lâminas de abobrinha", "carne, ricota e tomate", "4 porções", 30, 180, "2 abobrinhas grandes em lâminas", ["300 g de carne moída refogada", "150 g de ricota amassada", "1 xícara (chá) de molho de tomate", "100 g de muçarela ralada", "1 colher (chá) de orégano", "sal e pimenta a gosto"], "Grelhe as lâminas por 3 minutos antes de enrolar para retirar umidade."),
    R("Batata duchesse recheada com queijo e alho-poró", SPECIAL_CATEGORIES[2], "stuffed", "os montinhos de batata", "queijo, alho-poró e noz-moscada", "10 unidades", 34, 190, "600 g de purê de batata bem seco", ["2 gemas", "100 g de muçarela em cubos", "1/3 de xícara (chá) de alho-poró fatiado", "1 colher (sopa) de manteiga", "1 pitada de noz-moscada", "sal e pimenta a gosto"], "Use saco de confeitar para formar bordas altas ao redor do recheio."),
    R("Polenta cremosa com ragu e parmesão", SPECIAL_CATEGORIES[2], "gratin", "a polenta cremosa", "ragu de carne, parmesão e tomilho", "4 porções", 25, 180, "3 xícaras (chá) de polenta cremosa pronta", ["2 xícaras (chá) de ragu de carne quente", "60 g de parmesão ralado", "1 colher (chá) de tomilho", "1 colher (sopa) de manteiga", "sal e pimenta a gosto"], "Use os componentes já quentes; a Air Fryer entra apenas para unir e gratinar."),
    R("Nhoque de abóbora com manteiga de sálvia", SPECIAL_CATEGORIES[2], "roast", "os nhoques de abóbora", "sálvia, parmesão e manteiga", "4 porções", 26, 190, "500 g de nhoque de abóbora pré-cozido", ["1 colher (sopa) de manteiga derretida", "1 colher (chá) de sálvia seca", "40 g de parmesão ralado", "1 colher (chá) de azeite", "sal e pimenta a gosto"], "Seque o nhoque depois de cozinhar para ele criar bordas douradas."),
    R("Mac and cheese em ramequins", SPECIAL_CATEGORIES[2], "gratin", "o macarrão cozido", "cheddar, parmesão e noz-moscada", "4 porções", 26, 180, "3 xícaras (chá) de macarrão caracol cozido", ["1 xícara (chá) de molho branco", "150 g de cheddar ralado", "40 g de parmesão ralado", "1 pitada de noz-moscada", "2 colheres (sopa) de farinha panko", "sal e pimenta a gosto"], "Misture o queijo ao molho ainda quente antes de levar aos ramequins."),
    R("Torta de polenta com frango e quiabo", SPECIAL_CATEGORIES[2], "gratin", "a base de polenta", "frango, quiabo e queijo", "6 porções", 36, 180, "3 xícaras (chá) de polenta firme", ["2 xícaras (chá) de frango desfiado", "1 xícara (chá) de quiabo em rodelas já dourado", "1 xícara (chá) de molho de tomate", "120 g de queijo meia-cura ralado", "sal e pimenta a gosto"], "Pressione a polenta no fundo e nas laterais do refratário antes de colocar o recheio."),
    R("Wrap gratinado de carne, feijão e queijo", SPECIAL_CATEGORIES[2], "gratin", "os wraps", "carne, feijão e queijo", "4 unidades", 24, 190, "4 tortillas médias", ["300 g de carne moída refogada", "1 xícara (chá) de feijão cozido e escorrido", "120 g de muçarela ralada", "1/2 xícara (chá) de molho de tomate", "2 colheres (sopa) de cebola-roxa", "sal e cominho a gosto"], "Dobre as pontas para dentro e coloque a emenda voltada para baixo."),
    R("Shakshuka rápida com queijo e ervas", SPECIAL_CATEGORIES[2], "egg", "os ovos no molho", "tomate, pimentão e queijo", "3 porções", 24, 180, "5 ovos", ["1 e 1/2 xícara (chá) de molho de tomate", "1/2 pimentão vermelho picado", "1/2 cebola picada", "80 g de queijo minas em cubos", "1 colher (chá) de cominho", "sal, pimenta e salsinha a gosto"], "Aqueça o molho por 6 minutos antes de abrir os ovos por cima."),
    R("Moqueca individual de peixe e coco", SPECIAL_CATEGORIES[2], "gratin", "os cubos de peixe", "leite de coco, pimentão e coentro", "3 porções", 27, 180, "500 g de peixe firme em cubos", ["1/2 xícara (chá) de leite de coco", "1 tomate em rodelas", "1/2 pimentão amarelo em tiras", "1/2 cebola em rodelas", "1 colher (sopa) de azeite de dendê", "coentro, sal e pimenta a gosto"], "Use ramequins fundos e apoie-os em uma assadeira pequena para transportar sem derramar."),
    R("Bolinho de risoto recheado com cogumelos", SPECIAL_CATEGORIES[2], "breaded", "os bolinhos de risoto", "cogumelos, muçarela e panko", "12 unidades", 30, 190, "2 xícaras (chá) de risoto frio", ["1 xícara (chá) de cogumelos picados e dourados", "100 g de muçarela em cubos", "1 ovo batido", "1 xícara (chá) de farinha panko", "azeite para borrifar, sal e pimenta a gosto"], "O risoto deve estar bem gelado para envolver o recheio sem grudar."),
    R("Cuscuz marroquino assado com legumes", SPECIAL_CATEGORIES[2], "bake", "o cuscuz hidratado", "abobrinha, tomate e grão-de-bico", "4 porções", 25, 180, "2 xícaras (chá) de cuscuz marroquino hidratado", ["1/2 abobrinha em cubos pequenos", "1 tomate sem sementes em cubos", "1 xícara (chá) de grão-de-bico cozido", "2 colheres (sopa) de azeite", "2 colheres (sopa) de salsinha", "sal e cominho a gosto"], "Corte os legumes pequenos para que fiquem macios no mesmo tempo do cuscuz."),
    R("Mini torta de carne com ervilha e páprica", SPECIAL_CATEGORIES[2], "pastry", "as mini tortas", "carne, ervilha e páprica", "6 unidades", 32, 180, "300 g de massa pronta para torta", ["300 g de carne moída refogada", "1/2 xícara (chá) de ervilha", "1 tomate sem sementes picado", "1/2 colher (chá) de páprica", "1 gema para pincelar", "sal e pimenta a gosto"], "Recheie somente até três quartos da forma para fechar a tampa sem vazamentos."),
    R("Lasanha de berinjela à bolonhesa", SPECIAL_CATEGORIES[2], "gratin", "as lâminas de berinjela", "bolonhesa, ricota e muçarela", "4 porções", 35, 180, "2 berinjelas em lâminas finas", ["2 xícaras (chá) de molho bolonhesa", "150 g de ricota amassada", "150 g de muçarela ralada", "1 colher (sopa) de azeite", "1 colher (chá) de orégano", "sal a gosto"], "Asse as lâminas por 6 minutos antes da montagem para controlar a umidade."),
    R("Caçarola de batata, frango e alho-poró", SPECIAL_CATEGORIES[2], "gratin", "as lâminas de batata", "frango, alho-poró e creme", "5 porções", 38, 180, "500 g de batata em lâminas finas pré-cozidas", ["2 xícaras (chá) de frango desfiado", "1/2 xícara (chá) de alho-poró fatiado", "1 xícara (chá) de creme de leite", "150 g de muçarela ralada", "sal, pimenta e noz-moscada a gosto"], "Pré-cozinhe a batata até ficar flexível, mas ainda firme."),
    R("Ravióli assado com tomate cremoso", SPECIAL_CATEGORIES[2], "gratin", "os raviólis cozidos", "tomate, creme e parmesão", "4 porções", 25, 180, "500 g de ravióli fresco cozido por 2 minutos", ["1 xícara (chá) de molho de tomate", "1/2 xícara (chá) de creme de leite", "60 g de parmesão ralado", "8 tomates-cereja em metades", "1 colher (sopa) de manjericão", "sal e pimenta a gosto"], "Ferva o ravióli só até começar a amolecer; ele termina de cozinhar no molho."),
    R("Fritada de batata, chouriço e pimentão", SPECIAL_CATEGORIES[2], "egg", "a mistura de ovos", "batata, chouriço e pimentão", "4 porções", 30, 170, "6 ovos", ["300 g de batata cozida em cubos", "150 g de chouriço ou calabresa em rodelas", "1/2 pimentão em cubos", "1/2 cebola picada", "2 colheres (sopa) de salsinha", "sal e pimenta a gosto"], "Doure a batata e o chouriço por 6 minutos antes de adicionar os ovos."),
    # Doces e Sobremesas
    R("Cinnamon roll com calda de laranja", SPECIAL_CATEGORIES[3], "bake", "os rolinhos de canela", "canela, açúcar mascavo e laranja", "8 unidades", 32, 170, "400 g de massa fresca para pão doce", ["3 colheres (sopa) de manteiga", "1/3 de xícara (chá) de açúcar mascavo", "1 colher (sopa) de canela", "1/2 xícara (chá) de açúcar de confeiteiro", "2 colheres (sopa) de suco de laranja", "raspas de 1/2 laranja"], "Regue com a calda apenas quando os rolinhos estiverem mornos."),
    R("Brownie cheesecake de framboesa", SPECIAL_CATEGORIES[3], "bake", "a massa marmorizada", "chocolate, cream cheese e framboesa", "8 pedaços", 32, 160, "200 g de chocolate meio amargo derretido", ["100 g de manteiga", "3 ovos", "3/4 de xícara (chá) de açúcar", "1/2 xícara (chá) de farinha de trigo", "150 g de cream cheese", "1/2 xícara (chá) de framboesas"], "Misture o cream cheese apenas em movimentos largos para manter o efeito marmorizado."),
    R("Torta de maçã com caramelo e amêndoas", SPECIAL_CATEGORIES[3], "pastry", "a torta", "maçã, caramelo e amêndoas", "6 porções", 34, 170, "300 g de massa folhada gelada", ["3 maçãs em fatias finas", "3 colheres (sopa) de açúcar mascavo", "1 colher (chá) de canela", "3 colheres (sopa) de doce de leite", "3 colheres (sopa) de amêndoas laminadas", "1 gema para pincelar"], "Disponha as maçãs em camada fina para a base assar antes de o recheio soltar líquido."),
    R("Creme brûlée de coco e café", SPECIAL_CATEGORIES[3], "bake", "o creme de coco", "café, coco e baunilha", "4 unidades", 30, 150, "4 gemas", ["1 xícara (chá) de leite de coco", "1/3 de xícara (chá) de açúcar", "1 colher (chá) de café solúvel", "1/2 colher (chá) de baunilha", "2 colheres (sopa) de açúcar demerara para a crosta"], "Gele o creme e caramelize o açúcar em poucos minutos, observando sem se afastar."),
    R("Petit gâteau de goiabada com queijo", SPECIAL_CATEGORIES[3], "bake", "a massa do bolinho", "goiabada, queijo e baunilha", "4 unidades", 20, 180, "150 g de goiabada cremosa", ["100 g de manteiga", "2 ovos", "2 gemas", "1/3 de xícara (chá) de farinha de trigo", "80 g de queijo meia-cura em cubos", "1/2 colher (chá) de baunilha"], "O centro deve balançar levemente ao sair; faça uma unidade de teste para ajustar o ponto."),
    R("Cookie recheado com chocolate e avelã", SPECIAL_CATEGORIES[3], "stuffed", "os discos de cookie", "chocolate, avelã e baunilha", "8 unidades", 24, 170, "1 e 1/2 xícara (chá) de farinha de trigo", ["100 g de manteiga", "1/2 xícara (chá) de açúcar mascavo", "1 ovo", "1/2 colher (chá) de baunilha", "8 colheres (chá) de creme de avelã congelado", "1/2 colher (chá) de fermento químico"], "Congele pequenas porções do creme de avelã para rechear sem vazamentos."),
    R("Churros bites com açúcar e canela", SPECIAL_CATEGORIES[3], "bake", "os pedaços de churros", "canela, manteiga e doce de leite", "20 unidades", 26, 190, "1 xícara (chá) de água", ["2 colheres (sopa) de manteiga", "1 xícara (chá) de farinha de trigo", "1 ovo", "1/3 de xícara (chá) de açúcar", "1 colher (chá) de canela", "1/2 xícara (chá) de doce de leite para servir"], "Modele porções pequenas e iguais com saco de confeitar para assarem por completo."),
    R("Torta basca individual de baunilha", SPECIAL_CATEGORIES[3], "bake", "o creme de queijo", "cream cheese, baunilha e limão", "4 unidades", 28, 190, "300 g de cream cheese", ["2 ovos", "1/2 xícara (chá) de açúcar", "1/2 xícara (chá) de creme de leite", "1 colher (sopa) de farinha de trigo", "1 colher (chá) de baunilha", "raspas de 1/2 limão"], "O topo deve ficar bem escuro, enquanto o centro permanece cremoso e tremendo levemente."),
    R("Crumble de abacaxi, coco e gengibre", SPECIAL_CATEGORIES[3], "sweet", "o abacaxi", "coco, gengibre e aveia", "5 porções", 27, 180, "3 xícaras (chá) de abacaxi em cubos", ["1/2 xícara (chá) de aveia em flocos", "1/2 xícara (chá) de coco em flocos", "3 colheres (sopa) de açúcar mascavo", "3 colheres (sopa) de manteiga", "1/2 colher (chá) de gengibre ralado"], "Escorra o excesso de caldo do abacaxi antes de cobrir com a farofa."),
    R("Trouxinha de morango e chocolate", SPECIAL_CATEGORIES[3], "pastry", "as trouxinhas", "morango, chocolate e baunilha", "8 unidades", 22, 180, "8 quadrados de massa folhada gelada", ["8 morangos pequenos e secos", "100 g de chocolate meio amargo em pedaços", "1 colher (chá) de açúcar", "1/2 colher (chá) de baunilha", "1 gema para pincelar", "açúcar de confeiteiro para finalizar"], "Seque bem os morangos e feche as pontas da massa no centro."),
    R("Pera folhada com mel e gorgonzola", SPECIAL_CATEGORIES[3], "pastry", "as peras envolvidas em massa", "mel, gorgonzola e nozes", "4 unidades", 30, 180, "2 peras firmes cortadas ao meio", ["250 g de massa folhada em tiras", "80 g de gorgonzola", "2 colheres (sopa) de mel", "3 colheres (sopa) de nozes picadas", "1 gema para pincelar"], "Use pouco queijo para equilibrar o doce e evitar que o recheio transborde."),
    R("Blondie de chocolate branco e castanha-do-pará", SPECIAL_CATEGORIES[3], "bake", "a massa de blondie", "chocolate branco, castanha e baunilha", "8 pedaços", 30, 160, "180 g de chocolate branco derretido", ["100 g de manteiga", "2 ovos", "1/2 xícara (chá) de açúcar", "3/4 de xícara (chá) de farinha de trigo", "1/2 xícara (chá) de castanha-do-pará picada", "1/2 colher (chá) de baunilha"], "Retire quando o centro ainda estiver ligeiramente úmido; ele firma ao esfriar."),
    R("Financier de amêndoas, limão e mel", SPECIAL_CATEGORIES[3], "bake", "a massa de amêndoas", "amêndoas, limão e mel", "8 unidades", 27, 170, "1 xícara (chá) de farinha de amêndoas", ["4 claras", "80 g de manteiga dourada", "1/2 xícara (chá) de açúcar", "2 colheres (sopa) de farinha de trigo", "1 colher (sopa) de mel", "raspas de 1 limão"], "Doure a manteiga até perfumar, deixe amornar e só então misture às claras."),
    R("Tortinha de limão com merengue", SPECIAL_CATEGORIES[3], "pastry", "as tortinhas", "limão, leite condensado e merengue", "6 unidades", 26, 160, "6 bases pequenas de massa doce pré-assadas", ["1/2 lata de leite condensado", "1/3 de xícara (chá) de suco de limão", "raspas de 1 limão", "2 claras", "4 colheres (sopa) de açúcar", "1 pitada de sal"], "Doure o merengue por poucos minutos e acompanhe sem se afastar da Air Fryer."),
    R("Cannoli assado de ricota e chocolate", SPECIAL_CATEGORIES[3], "pastry", "os tubos de massa", "ricota, chocolate e laranja", "8 unidades", 24, 180, "8 discos de massa para pastel", ["200 g de ricota peneirada", "3 colheres (sopa) de açúcar de confeiteiro", "50 g de chocolate picado", "raspas de 1/2 laranja", "1 gema para pincelar", "1 colher (chá) de manteiga"], "Asse a massa em cilindros metálicos e recheie somente depois de fria."),
    R("Bolinho vulcão de doce de leite", SPECIAL_CATEGORIES[3], "stuffed", "os bolinhos", "doce de leite, canela e baunilha", "6 unidades", 27, 170, "1 xícara (chá) de farinha de trigo", ["2 ovos", "1/2 xícara (chá) de leite", "1/3 de xícara (chá) de açúcar", "3 colheres (sopa) de manteiga", "1 colher (chá) de fermento químico", "6 colheres (chá) de doce de leite congelado", "canela e baunilha a gosto"], "Congele o doce de leite em pequenas porções para formar o centro cremoso."),
    R("Cobbler de pêssego e amêndoas", SPECIAL_CATEGORIES[3], "sweet", "os pêssegos", "amêndoas, canela e baunilha", "5 porções", 30, 170, "4 pêssegos em fatias", ["1/2 xícara (chá) de farinha de trigo", "1/3 de xícara (chá) de açúcar", "1/3 de xícara (chá) de leite", "2 colheres (sopa) de manteiga", "3 colheres (sopa) de amêndoas laminadas", "canela e baunilha a gosto"], "Distribua a massa em pequenas porções sobre a fruta, deixando espaços para o vapor sair."),
    R("Pudim de pão com chocolate e café", SPECIAL_CATEGORIES[3], "bake", "a mistura de pão", "chocolate, café e canela", "6 porções", 35, 160, "3 pães franceses amanhecidos em cubos", ["2 xícaras (chá) de leite", "3 ovos", "1/2 xícara (chá) de açúcar", "80 g de chocolate picado", "1 colher (sopa) de café solúvel", "1/2 colher (chá) de canela"], "Deixe o pão absorver o líquido por 10 minutos antes de assar."),
    R("Brigadeirão de café em ramequins", SPECIAL_CATEGORIES[3], "bake", "o creme de chocolate", "chocolate, café e leite condensado", "6 unidades", 32, 160, "1 lata de leite condensado", ["1 caixa de creme de leite", "3 ovos", "4 colheres (sopa) de cacau em pó", "1 colher (sopa) de café solúvel", "1 colher (sopa) de manteiga", "chocolate granulado para finalizar"], "Cubra os ramequins com papel-alumínio bem preso para a superfície ficar lisa."),
    R("Rosa folhada de maçã e canela", SPECIAL_CATEGORIES[3], "pastry", "as tiras de massa com maçã", "maçã, canela e geleia", "6 unidades", 30, 180, "250 g de massa folhada em tiras", ["2 maçãs vermelhas em lâminas finas", "3 colheres (sopa) de geleia de damasco", "1 colher (chá) de canela", "1 colher (sopa) de açúcar", "1 colher (sopa) de suco de limão"], "Amoleça as lâminas de maçã por 2 minutos para enrolarem sem quebrar."),
    R("Suflê de chocolate e laranja", SPECIAL_CATEGORIES[3], "bake", "a massa de suflê", "chocolate, laranja e baunilha", "4 unidades", 22, 170, "120 g de chocolate meio amargo derretido", ["3 ovos, com claras e gemas separadas", "2 colheres (sopa) de açúcar", "1 colher (sopa) de manteiga", "raspas de 1 laranja", "1/2 colher (chá) de baunilha", "1 pitada de sal"], "Sirva imediatamente: o centro permanece leve e perde volume ao esfriar."),
    R("Cheesecake de banana com caramelo salgado", SPECIAL_CATEGORIES[3], "bake", "o creme de cheesecake", "banana, caramelo e flor de sal", "6 porções", 32, 150, "300 g de cream cheese", ["2 ovos", "1 banana madura amassada", "1/2 xícara (chá) de açúcar", "1/2 xícara (chá) de creme de leite", "4 colheres (sopa) de calda de caramelo", "1 pitada de flor de sal"], "Gele por pelo menos 3 horas e finalize com caramelo apenas ao servir."),
    R("Bolo de coco com calda de maracujá", SPECIAL_CATEGORIES[3], "bake", "a massa de coco", "coco, maracujá e baunilha", "8 pedaços", 34, 160, "1 xícara (chá) de farinha de trigo", ["1/2 xícara (chá) de coco ralado", "2 ovos", "1/2 xícara (chá) de leite de coco", "1/2 xícara (chá) de açúcar", "1 colher (chá) de fermento químico", "polpa de 1 maracujá e 2 colheres (sopa) de açúcar para a calda"], "Ferva a calda separadamente e despeje sobre o bolo já frio."),
    R("Sanduíche de cookie de amendoim e chocolate", SPECIAL_CATEGORIES[3], "stuffed", "os discos de cookie", "amendoim, chocolate e baunilha", "6 unidades", 25, 170, "1 xícara (chá) de pasta de amendoim", ["1/2 xícara (chá) de açúcar mascavo", "1 ovo", "1/2 colher (chá) de baunilha", "1/2 colher (chá) de bicarbonato", "120 g de chocolate meio amargo", "1/3 de xícara (chá) de creme de leite"], "Recheie apenas quando os cookies estiverem frios para a ganache não escorrer."),
    R("Fondant de chocolate com centro de maracujá", SPECIAL_CATEGORIES[3], "stuffed", "os bolinhos de chocolate", "chocolate, maracujá e baunilha", "4 unidades", 21, 180, "150 g de chocolate meio amargo derretido", ["80 g de manteiga", "2 ovos", "2 gemas", "1/3 de xícara (chá) de açúcar", "1/3 de xícara (chá) de farinha de trigo", "4 colheres (chá) de creme de maracujá congelado"], "Congele o creme em porções e faça uma unidade de teste para acertar o centro fluido."),
]
